In [1]:
import boto3
import pandas as pd
import numpy as np

AWS_REGION = "ap-south-1"
BUCKET_NAME = "krushang-beverage-ml-2026"

RAW_KEY = "raw/survey_results.csv"
PROCESSED_PREFIX = "processed"

s3 = boto3.client("s3", region_name=AWS_REGION)

print("AWS Region:", AWS_REGION)
print("S3 Bucket:", BUCKET_NAME)

AWS Region: ap-south-1
S3 Bucket: krushang-beverage-ml-2026

In [2]:
response = s3.get_object(
    Bucket=BUCKET_NAME,
    Key=RAW_KEY
)

df = pd.read_csv(response["Body"])

print("Raw dataset shape:", df.shape)
df.head(20)

Raw dataset shape: (30010, 17)

,respondent_id,age,gender,zone,occupation,income_levels,consume_frequency(weekly),current_brand,preferable_consumption_size,awareness_of_other_brands,reasons_for_choosing_brands,flavor_preference,purchase_channel,packaging_preference,health_concerns,typical_consumption_situations,price_range
0,R00001,30,M,Urban,Working Professional,<10L,3-4 times,Newcomer,Medium (500 ml),0 to 1,Price,Traditional,Online,Simple,Medium (Moderately health-conscious),"Active (eg. Sports, gym)",100-150
1,R00002,46,F,Metro,Working Professional,> 35L,5-7 times,Established,Medium (500 ml),2 to 4,Quality,Exotic,Retail Store,Premium,Medium (Moderately health-conscious),Social (eg. Parties),200-250
2,R00003,41,F,Rural,Working Professional,> 35L,3-4 times,Newcomer,Medium (500 ml),2 to 4,Availability,Traditional,Retail Store,Premium,Medium (Moderately health-conscious),"Active (eg. Sports, gym)",200-250
3,R00004,33,F,Urban,Working Professional,16L - 25L,5-7 times,Newcomer,Medium (500 ml),0 to 1,Brand Reputation,Exotic,Online,Eco-Friendly,Low (Not very concerned),"Active (eg. Sports, gym)",150-200
4,R00005,23,M,Metro,Student,NaN,3-4 times,Established,Medium (500 ml),0 to 1,Availability,Traditional,Online,Premium,Medium (Moderately health-conscious),"Active (eg. Sports, gym)",50-100
5,R00006,22,F,Urban,Student,NaN,5-7 times,Established,Large (1 L),2 to 4,Price,Traditional,Online,Simple,Low (Not very concerned),"Active (eg. Sports, gym)",100-150
6,R00007,45,F,Urban,Entrepreneur,10L - 15L,5-7 times,Newcomer,Medium (500 ml),2 to 4,Price,Traditional,Online,Premium,High (Very health-conscious),Social (eg. Parties),200-250
7,R00008,31,M,Urban,Entrepreneur,26L - 35L,5-7 times,Established,Medium (500 ml),above 4,Brand Reputation,Exotic,Retail Store,Simple,High (Very health-conscious),"Active (eg. Sports, gym)",200-250
8,R00009,27,F,Semi-Urban,Working Professional,<10L,5-7 times,Newcomer,Small (250 ml),2 to 4,Availability,Exotic,Retail Store,Eco-Friendly,Medium (Moderately health-conscious),Social (eg. Parties),100-150
9,R00010,49,F,Semi-Urban,Entrepreneur,10L - 15L,5-7 times,Newcomer,Medium (500 ml),2 to 4,Price,Traditional,Retail Store,Simple,High (Very health-conscious),"Active (eg. Sports, gym)",200-250
10,R00011,44,F,Urban,Entrepreneur,10L - 15L,3-4 times,Newcomer,Medium (500 ml),above 4,Price,Traditional,Online,Simple,High (Very health-conscious),Casual (eg. At home),200-250
11,R00012,23,F,Urban,Student,NaN,0-2 times,Established,Small (250 ml),0 to 1,Price,Exotic,Retail Store,Premium,Low (Not very concerned),Social (eg. Parties),50-100
12,R00013,19,M,Urban,Working Professional,<10L,0-2 times,Established,Small (250 ml),0 to 1,Price,Exotic,Online,Premium,Medium (Moderately health-conscious),Social (eg. Parties),100-150
13,R00014,24,M,Urban,Working Professional,<10L,0-2 times,Established,Medium (500 ml),0 to 1,Price,Traditional,Online,Premium,Low (Not very concerned),"Active (eg. Sports, gym)",100-150
14,R00015,22,M,Metro,Student,NaN,3-4 times,Established,Small (250 ml),0 to 1,Price,Traditional,Retail Store,Simple,Medium (Moderately health-conscious),"Active (eg. Sports, gym)",100-150
15,R00016,32,F,Metro,Working Professional,16L - 25L,3-4 times,Established,Medium (500 ml),2 to 4,Quality,Exotic,Retail Store,Premium,High (Very health-conscious),Social (eg. Parties),200-250
16,R00017,44,M,Metro,Working Professional,16L - 25L,0-2 times,Established,Medium (500 ml),0 to 1,Quality,Traditional,Retail Store,Premium,High (Very health-conscious),Casual (eg. At home),150-200
17,R00018,56,M,Metro,Entrepreneur,16L - 25L,3-4 times,Newcomer,Large (1 L),above 4,Availability,Exotic,Retail Store,Eco-Friendly,Medium (Moderately health-conscious),Casual (eg. At home),200-250
18,R00019,54,M,Urban,Working Professional,26L - 35L,3-4 times,Newcomer,Large (1 L),0 to 1,Quality,Traditional,Online,Premium,Medium (Moderately health-conscious),Casual (eg. At home),200-250
19,R00020,37,F,Urban,Entrepreneur,10L - 15L,5-7 times,Established,Medium (500 ml),above 4,Price,Exotic,Online,Eco-Friendly,Medium (Moderately health-conscious),"Active (eg. Sports, gym)",200-250

In [3]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Shape: (30010, 17)

Columns:
['respondent_id', 'age', 'gender', 'zone', 'occupation', 'income_levels', 'consume_frequency(weekly)', 'current_brand', 'preferable_consumption_size', 'awareness_of_other_brands', 'reasons_for_choosing_brands', 'flavor_preference', 'purchase_channel', 'packaging_preference', 'health_concerns', 'typical_consumption_situations', 'price_range']

Missing values:
respondent_id                        0
age                                  0
gender                               0
zone                                 0
occupation                           0
income_levels                     8064
consume_frequency(weekly)            8
current_brand                        0
preferable_consumption_size          0
awareness_of_other_brands            0
reasons_for_choosing_brands          0
flavor_preference                    0
purchase_channel                    10
packaging_preference                 0
health_concerns                      0
typical_consumption_situations       0
price_range                          0
dtype: int64

Duplicate rows: 10

In [4]:
# Step 1: Remove exact duplicate rows

print("Shape before duplicate removal:", df.shape)
print("Exact duplicates:", df.duplicated().sum())

df = df.drop_duplicates().copy()

print("Shape after duplicate removal:", df.shape)

Shape before duplicate removal: (30010, 17)
Exact duplicates: 10
Shape after duplicate removal: (30000, 17)

In [5]:
# Step 2: Check categorical inconsistencies

for col in ["zone", "current_brand"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- zone ---
zone
Metro         11911
Urban         10688
Semi-Urban     5275
Rural          2117
urbna             5
Metor             4
Name: count, dtype: int64

--- current_brand ---
current_brand
Established    15447
Newcomer       14503
newcomer          30
Establishd        20
Name: count, dtype: int64

In [6]:
# Step 3: Fix confirmed categorical inconsistencies

df["zone"] = df["zone"].replace({
    "urbna": "Urban",
    "Metor": "Metro"
})

df["current_brand"] = df["current_brand"].replace({
    "newcomer": "Newcomer",
    "Establishd": "Established"
})

In [7]:
print(df["zone"].value_counts(dropna=False))
print()
print(df["current_brand"].value_counts(dropna=False))

zone
Metro         11915
Urban         10693
Semi-Urban     5275
Rural          2117
Name: count, dtype: int64

current_brand
Established    15467
Newcomer       14533
Name: count, dtype: int64

In [8]:
# Step 4: Handle deterministic missing values

df["income_levels"] = df["income_levels"].fillna("Not Reported")

print("Missing values after income handling:")
print(
    df[
        [
            "income_levels",
            "consume_frequency(weekly)",
            "purchase_channel"
        ]
    ].isnull().sum()
)

Missing values after income handling:
income_levels                 0
consume_frequency(weekly)     8
purchase_channel             10
dtype: int64

In [9]:
# Step 5: Check logical age / occupation anomalies

age_group_temp = pd.cut(
    df["age"],
    bins=[17, 25, 35, 45, 55, 70, float("inf")],
    labels=["18-25", "26-35", "36-45", "46-55", "56-70", "70+"]
)

print("Age range:", df["age"].min(), "to", df["age"].max())

print("\nStudents aged 56-70:")
print(
    df[
        (age_group_temp == "56-70") &
        (df["occupation"] == "Student")
    ][["respondent_id", "age", "occupation"]]
)

print("\nRespondents aged above 70:")
print(
    df[
        age_group_temp == "70+"
    ][["respondent_id", "age", "occupation"]]
)

print("\nTotal suspicious rows:",
      (
          ((age_group_temp == "56-70") & (df["occupation"] == "Student"))
          | (age_group_temp == "70+")
      ).sum()
)

Age range: 18 to 604

Students aged 56-70:
      respondent_id  age occupation
182          R00183   65    Student
3526         R03525   59    Student
3527         R03526   61    Student
3772         R03771   63    Student
4033         R04032   64    Student
6545         R06543   66    Student
6594         R06592   70    Student
6648         R06646   63    Student
7420         R07418   60    Student
7596         R07594   59    Student
7841         R07838   68    Student
9090         R09086   65    Student
9198         R09194   67    Student
11877        R11872   60    Student
12031        R12026   68    Student
12471        R12466   62    Student
15711        R15706   61    Student
16230        R16225   59    Student
16829        R16824   64    Student
17202        R17197   66    Student
19103        R19097   60    Student
20218        R20212   68    Student
21422        R21416   68    Student
24252        R24244   64    Student
24885        R24877   69    Student
25090        R25081   69    Student
25133        R25124   66    Student
25443        R25434   66    Student
25544        R25535   56    Student
25723        R25714   58    Student
25819        R25810   60    Student
26066        R26057   63    Student
26851        R26842   58    Student
28578        R28569   68    Student
28910        R28901   66    Student

Respondents aged above 70:
      respondent_id  age            occupation
3099         R03098  453  Working Professional
6262         R06260  428          Entrepreneur
12403        R12398  604               Retired
22549        R22542  457  Working Professional
22918        R22911  267  Working Professional
24958        R24950  285  Working Professional
24960        R24952  192               Student
25105        R25096  203  Working Professional
28770        R28761  428  Working Professional

Total suspicious rows: 44

In [10]:
# Step 6: Profile suspicious Student records

student_anomalies = df[
    (df["occupation"] == "Student") &
    (df["age"] > 35)
].copy()

student_anomalies[
    [
        "respondent_id",
        "age",
        "gender",
        "zone",
        "income_levels",
        "consume_frequency(weekly)",
        "current_brand",
        "preferable_consumption_size",
        "awareness_of_other_brands",
        "purchase_channel",
        "health_concerns"
    ]
]

,respondent_id,age,gender,zone,income_levels,consume_frequency(weekly),current_brand,preferable_consumption_size,awareness_of_other_brands,purchase_channel,health_concerns
182,R00183,65,F,Urban,Not Reported,5-7 times,Established,Large (1 L),above 4,Retail Store,Medium (Moderately health-conscious)
3526,R03525,59,F,Semi-Urban,Not Reported,0-2 times,Established,Medium (500 ml),0 to 1,Retail Store,Medium (Moderately health-conscious)
3527,R03526,61,M,Semi-Urban,Not Reported,0-2 times,Newcomer,Small (250 ml),2 to 4,Retail Store,High (Very health-conscious)
3772,R03771,63,M,Metro,Not Reported,5-7 times,Newcomer,Medium (500 ml),2 to 4,Online,High (Very health-conscious)
4033,R04032,64,M,Urban,Not Reported,3-4 times,Established,Medium (500 ml),0 to 1,Retail Store,High (Very health-conscious)
6545,R06543,66,F,Urban,Not Reported,5-7 times,Newcomer,Medium (500 ml),0 to 1,Retail Store,High (Very health-conscious)
6594,R06592,70,M,Semi-Urban,Not Reported,5-7 times,Established,Medium (500 ml),0 to 1,Retail Store,Medium (Moderately health-conscious)
6648,R06646,63,F,Semi-Urban,Not Reported,0-2 times,Established,Medium (500 ml),2 to 4,Retail Store,High (Very health-conscious)
7420,R07418,60,F,Rural,Not Reported,3-4 times,Established,Small (250 ml),0 to 1,Retail Store,Medium (Moderately health-conscious)
7596,R07594,59,M,Urban,Not Reported,5-7 times,Newcomer,Medium (500 ml),2 to 4,Online,High (Very health-conscious)
7841,R07838,68,F,Metro,Not Reported,0-2 times,Established,Large (1 L),0 to 1,Retail Store,High (Very health-conscious)
9090,R09086,65,F,Urban,Not Reported,3-4 times,Newcomer,Small (250 ml),0 to 1,Online,High (Very health-conscious)
9198,R09194,67,M,Urban,Not Reported,3-4 times,Established,Large (1 L),0 to 1,Retail Store,Low (Not very concerned)
11877,R11872,60,M,Metro,Not Reported,0-2 times,Established,Small (250 ml),0 to 1,Retail Store,High (Very health-conscious)
12031,R12026,68,M,Urban,Not Reported,3-4 times,Newcomer,Large (1 L),2 to 4,Retail Store,High (Very health-conscious)
12471,R12466,62,F,Metro,Not Reported,5-7 times,Newcomer,Medium (500 ml),above 4,Retail Store,High (Very health-conscious)
15711,R15706,61,F,Metro,Not Reported,5-7 times,Newcomer,Medium (500 ml),2 to 4,Retail Store,High (Very health-conscious)
16230,R16225,59,M,Urban,Not Reported,5-7 times,Established,Medium (500 ml),2 to 4,Online,High (Very health-conscious)
16829,R16824,64,M,Semi-Urban,Not Reported,0-2 times,Established,Small (250 ml),above 4,Retail Store,High (Very health-conscious)
17202,R17197,66,M,Metro,Not Reported,0-2 times,Established,Medium (500 ml),0 to 1,Retail Store,Medium (Moderately health-conscious)
19103,R19097,60,M,Semi-Urban,Not Reported,0-2 times,Newcomer,Small (250 ml),0 to 1,Retail Store,Medium (Moderately health-conscious)
20218,R20212,68,F,Metro,Not Reported,3-4 times,Established,Medium (500 ml),0 to 1,Retail Store,High (Very health-conscious)
21422,R21416,68,F,Urban,Not Reported,0-2 times,Newcomer,Small (250 ml),2 to 4,Retail Store,High (Very health-conscious)
24252,R24244,64,F,Urban,Not Reported,5-7 times,Newcomer,Small (250 ml),0 to 1,Online,Low (Not very concerned)
24885,R24877,69,M,Urban,Not Reported,0-2 times,Established,Medium (500 ml),0 to 1,Retail Store,Low (Not very concerned)
24960,R24952,192,F,Urban,Not Reported,3-4 times,Newcomer,Medium (500 ml),0 to 1,Online,Low (Not very concerned)
25090,R25081,69,F,Semi-Urban,Not Reported,0-2 times,Newcomer,Medium (500 ml),0 to 1,Retail Store,High (Very health-conscious)
25133,R25124,66,F,Urban,Not Reported,0-2 times,Established,Small (250 ml),0 to 1,Online,High (Very health-conscious)
25443,R25434,66,M,Rural,Not Reported,0-2 times,Newcomer,Medium (500 ml),0 to 1,Retail Store,High (Very health-conscious)
25544,R25535,56,F,Rural,Not Reported,0-2 times,Established,Small (250 ml),0 to 1,Online,High (Very health-conscious)
25723,R25714,58,F,Urban,Not Reported,0-2 times,Newcomer,Small (250 ml),above 4,Retail Store,Medium (Moderately health-conscious)
25819,R25810,60,M,Urban,Not Reported,3-4 times,Newcomer,Large (1 L),2 to 4,Online,High (Very health-conscious)
26066,R26057,63,M,Semi-Urban,Not Reported,0-2 times,Newcomer,Small (250 ml),0 to 1,Online,High (Very health-conscious)
26851,R26842,58,F,Metro,Not Reported,0-2 times,Newcomer,Medium (500 ml),0 to 1,Retail Store,Low (Not very concerned)
28578,R28569,68,F,Metro,Not Reported,0-2 times,Established,Medium (500 ml),2 to 4,Online,Low (Not very concerned)
28910,R28901,66,M,Semi-Urban,Not Reported,3-4 times,Established,Small (250 ml),0 to 1,Online,Low (Not very concerned)

In [11]:
# Compare normal age patterns by occupation

df[df["age"] <= 70].groupby("occupation")["age"].agg(
    ["count", "min", "median", "mean", "max"]
).round(1)

                      count  min  median  mean  max
occupation
Entrepreneur           5000   18    36.0  37.4   70
Retired                1130   56    63.0  63.0   70
Student                8060   18    22.0  22.5   70
Working Professional  15801   18    34.0  34.7   70

In [12]:
# Income profile by occupation

pd.crosstab(
    df["occupation"],
    df["income_levels"],
    normalize="index"
).round(3)

income_levels,10L - 15L,16L - 25L,26L - 35L,<10L,> 35L,Not Reported
occupation,,,,,,
Entrepreneur,0.249,0.279,0.215,0.142,0.115,0.0
Retired,0.195,0.105,0.000,0.699,0.000,0.0
Student,0.000,0.000,0.000,0.000,0.000,1.0
Working Professional,0.239,0.278,0.177,0.200,0.106,0.0

In [13]:
# Create age groups

df["age_group"] = pd.cut(
    df["age"],
    bins=[17, 25, 35, 45, 55, 70, float("inf")],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-70",
        "70+"
    ]
)

In [14]:
# Remove logically inconsistent / invalid age records

outlier_conditions = (
    ((df["age_group"] == "56-70") & (df["occupation"] == "Student"))
    |
    (df["age_group"] == "70+")
)

print("Rows to remove:", outlier_conditions.sum())

df = df.loc[~outlier_conditions].copy()

print("Final shape:", df.shape)

Rows to remove: 44
Final shape: (29956, 18)

In [15]:
# Remaining missing values

df["consume_frequency(weekly)"] = df["consume_frequency(weekly)"].fillna(
    df["consume_frequency(weekly)"].mode()[0]
)

df["purchase_channel"] = df["purchase_channel"].fillna(
    df["purchase_channel"].mode()[0]
)

print("Remaining missing values:", df.isnull().sum().sum())
print("Shape:", df.shape)

Remaining missing values: 0
Shape: (29956, 18)

In [16]:
zone_map = {
    "Rural": 1,
    "Semi-Urban": 2,
    "Urban": 3,
    "Metro": 4
}

income_map = {
    "Not Reported": 0,
    "<10L": 1,
    "10L - 15L": 2,
    "16L - 25L": 3,
    "26L - 35L": 4,
    "> 35L": 5
}

df["income_levels"] = df["income_levels"].str.strip()

df["zone_num"] = df["zone"].map(zone_map)
df["income_num"] = df["income_levels"].map(income_map)

df["zas_score"] = df["zone_num"] * df["income_num"]

In [17]:
df["bsi"] = (
    (df["current_brand"] != "Established") &
    (df["reasons_for_choosing_brands"].isin(["Price", "Quality"]))
).astype(int)

In [18]:
print(df[["age_group", "zone_num", "income_num", "zas_score", "bsi"]].head())

  age_group  zone_num  income_num  zas_score  bsi
0     26-35         3           1          3    1
1     46-55         4           5         20    0
2     36-45         1           5          5    0
3     26-35         3           3          9    0
4     18-25         4           0          0    0

In [19]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["price_range", "respondent_id"])
y = df["price_range"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("\nTrain target distribution:")
print(y_train.value_counts(normalize=True).round(3))

print("\nTest target distribution:")
print(y_test.value_counts(normalize=True).round(3))

X_train: (22467, 20)
X_test : (7489, 20)

Train target distribution:
price_range
200-250    0.324
150-200    0.294
100-150    0.260
50-100     0.122
Name: proportion, dtype: float64

Test target distribution:
price_range
200-250    0.324
150-200    0.294
100-150    0.260
50-100     0.122
Name: proportion, dtype: float64

In [20]:
from sklearn.impute import SimpleImputer

# Columns with missing values
impute_cols = [
    "consume_frequency(weekly)",
    "purchase_channel"
]

# Fit ONLY on training data
cat_imputer = SimpleImputer(strategy="most_frequent")

X_train[impute_cols] = cat_imputer.fit_transform(
    X_train[impute_cols]
)

# Test only receives values learned from train
X_test[impute_cols] = cat_imputer.transform(
    X_test[impute_cols]
)

print("Learned training modes:")
for col, value in zip(impute_cols, cat_imputer.statistics_):
    print(f"{col}: {value}")

print("\nMissing train:", X_train[impute_cols].isnull().sum().sum())
print("Missing test :", X_test[impute_cols].isnull().sum().sum())

Learned training modes:
consume_frequency(weekly): 3-4 times
purchase_channel: Online

Missing train: 0
Missing test : 0

In [21]:
cf_map = {
    "0-2 times": 1,
    "3-4 times": 2,
    "5-7 times": 3
}

ab_map = {
    "0 to 1": 1,
    "2 to 4": 2,
    "above 4": 3
}

for data in [X_train, X_test]:
    data["cf_num"] = data["consume_frequency(weekly)"].map(cf_map)
    data["ab_num"] = data["awareness_of_other_brands"].map(ab_map)

    data["cf_ab_score"] = (
        data["cf_num"] /
        (data["cf_num"] + data["ab_num"])
    ).round(2)

print("Train shape:", X_train.shape)
print("Test shape :", X_test.shape)

print("\nMissing values:")
print("Train:", X_train.isnull().sum().sum())
print("Test :", X_test.isnull().sum().sum())

Train shape: (22467, 23)
Test shape : (7489, 23)

Missing values:
Train: 0
Test : 0

In [22]:
# Step 9: Finalize model features

drop_cols = [
    "age",
    "cf_num",
    "ab_num",
    "zone_num",
    "income_num"
]

X_train = X_train.drop(columns=drop_cols)
X_test  = X_test.drop(columns=drop_cols)

print("Train:", X_train.shape)
print("Test :", X_test.shape)

Train: (22467, 18)
Test : (7489, 18)

In [23]:
# Fixed ordinal mappings

age_group_map = {
    "18-25": 1,
    "26-35": 2,
    "36-45": 3,
    "46-55": 4,
    "56-70": 5
}

income_map = {
    "Not Reported": 0,
    "<10L": 1,
    "10L - 15L": 2,
    "16L - 25L": 3,
    "26L - 35L": 4,
    "> 35L": 5
}

health_map = {
    "Low (Not very concerned)": 1,
    "Medium (Moderately health-conscious)": 2,
    "High (Very health-conscious)": 3
}

freq_map = {
    "0-2 times": 1,
    "3-4 times": 2,
    "5-7 times": 3
}

size_map = {
    "Small (250 ml)": 1,
    "Medium (500 ml)": 2,
    "Large (1 L)": 3
}

for data in [X_train, X_test]:
    data["age_group"] = data["age_group"].astype(str).map(age_group_map)
    data["income_levels"] = data["income_levels"].map(income_map)
    data["health_concerns"] = data["health_concerns"].map(health_map)
    data["consume_frequency(weekly)"] = data["consume_frequency(weekly)"].map(freq_map)
    data["preferable_consumption_size"] = data["preferable_consumption_size"].map(size_map)

# Fixed target mapping
price_map = {
    "50-100": 0,
    "100-150": 1,
    "150-200": 2,
    "200-250": 3
}

y_train = y_train.map(price_map)
y_test  = y_test.map(price_map)

print("Missing train:", X_train.isna().sum().sum())
print("Missing test :", X_test.isna().sum().sum())
print("Train shape:", X_train.shape)

Missing train: 0
Missing test : 0
Train shape: (22467, 18)

In [24]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Remaining nominal categorical columns
cat_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()

print("Categorical columns:", cat_cols)

# Fit encoder ONLY on training data
ohe = OneHotEncoder(
    handle_unknown="ignore",
    drop="first",
    sparse_output=False
)

X_train_cat = ohe.fit_transform(X_train[cat_cols])
X_test_cat  = ohe.transform(X_test[cat_cols])

# Convert encoded arrays to DataFrames
encoded_cols = ohe.get_feature_names_out(cat_cols)

X_train_cat = pd.DataFrame(
    X_train_cat,
    columns=encoded_cols,
    index=X_train.index
)

X_test_cat = pd.DataFrame(
    X_test_cat,
    columns=encoded_cols,
    index=X_test.index
)

# Numeric features pass through unchanged
num_cols = X_train.columns.difference(cat_cols)

X_train_encoded = pd.concat(
    [X_train[num_cols], X_train_cat],
    axis=1
)

X_test_encoded = pd.concat(
    [X_test[num_cols], X_test_cat],
    axis=1
)

print("Encoded train:", X_train_encoded.shape)
print("Encoded test :", X_test_encoded.shape)

print("\nColumns identical:",
      X_train_encoded.columns.equals(X_test_encoded.columns))

print("Missing train:", X_train_encoded.isna().sum().sum())
print("Missing test :", X_test_encoded.isna().sum().sum())

Categorical columns: ['gender', 'zone', 'occupation', 'current_brand', 'awareness_of_other_brands', 'reasons_for_choosing_brands', 'flavor_preference', 'purchase_channel', 'packaging_preference', 'typical_consumption_situations']
Encoded train: (22467, 27)
Encoded test : (7489, 27)

Columns identical: True
Missing train: 0
Missing test : 0

In [25]:
from sklearn.model_selection import train_test_split

# Recreate the same untouched development/test split
X_dev_raw, X_final_test_raw, y_dev, y_final_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# Validation comes ONLY from the development data
X_model_train, X_val, y_model_train, y_val = train_test_split(
    X_dev_raw,
    y_dev,
    test_size=0.20,
    random_state=42,
    stratify=y_dev
)

print("Model train :", X_model_train.shape)
print("Validation  :", X_val.shape)
print("Final test  :", X_final_test_raw.shape)

print("\nOverall split:")
print(
    round(len(X_model_train)/len(X)*100, 1),
    round(len(X_val)/len(X)*100, 1),
    round(len(X_final_test_raw)/len(X)*100, 1)
)

Model train : (17973, 20)
Validation  : (4494, 20)
Final test  : (7489, 20)

Overall split:
60.0 15.0 25.0

In [26]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# --------------------------------------------------
# STEP 11: Fit preprocessing on MODEL TRAIN only
# --------------------------------------------------

train_prep = X_model_train.copy()
val_prep   = X_val.copy()

# 1. Train-only imputation
impute_cols = [
    "consume_frequency(weekly)",
    "purchase_channel"
]

imputer = SimpleImputer(strategy="most_frequent")

train_prep[impute_cols] = imputer.fit_transform(
    train_prep[impute_cols]
)

val_prep[impute_cols] = imputer.transform(
    val_prep[impute_cols]
)


# 2. Create cf_ab_score AFTER imputation
cf_map = {
    "0-2 times": 1,
    "3-4 times": 2,
    "5-7 times": 3
}

ab_map = {
    "0 to 1": 1,
    "2 to 4": 2,
    "above 4": 3
}

for data in [train_prep, val_prep]:
    data["cf_num"] = data["consume_frequency(weekly)"].map(cf_map)
    data["ab_num"] = data["awareness_of_other_brands"].map(ab_map)

    data["cf_ab_score"] = (
        data["cf_num"] /
        (data["cf_num"] + data["ab_num"])
    ).round(2)


# 3. Remove raw/helper features not used by final model
drop_cols = [
    "age",
    "cf_num",
    "ab_num",
    "zone_num",
    "income_num"
]

train_prep = train_prep.drop(columns=drop_cols)
val_prep   = val_prep.drop(columns=drop_cols)


# 4. Fixed ordinal mappings
age_group_map = {
    "18-25": 1,
    "26-35": 2,
    "36-45": 3,
    "46-55": 4,
    "56-70": 5
}

income_map = {
    "Not Reported": 0,
    "<10L": 1,
    "10L - 15L": 2,
    "16L - 25L": 3,
    "26L - 35L": 4,
    "> 35L": 5
}

health_map = {
    "Low (Not very concerned)": 1,
    "Medium (Moderately health-conscious)": 2,
    "High (Very health-conscious)": 3
}

freq_map = {
    "0-2 times": 1,
    "3-4 times": 2,
    "5-7 times": 3
}

size_map = {
    "Small (250 ml)": 1,
    "Medium (500 ml)": 2,
    "Large (1 L)": 3
}

for data in [train_prep, val_prep]:
    data["age_group"] = data["age_group"].astype(str).map(age_group_map)
    data["income_levels"] = data["income_levels"].map(income_map)
    data["health_concerns"] = data["health_concerns"].map(health_map)
    data["consume_frequency(weekly)"] = data["consume_frequency(weekly)"].map(freq_map)
    data["preferable_consumption_size"] = data["preferable_consumption_size"].map(size_map)


# 5. One-hot encoder fitted ONLY on model train
cat_cols = train_prep.select_dtypes(
    include=["object", "category"]
).columns.tolist()

num_cols = [
    c for c in train_prep.columns
    if c not in cat_cols
]

ohe = OneHotEncoder(
    handle_unknown="ignore",
    drop="first",
    sparse_output=False
)

train_cat = ohe.fit_transform(train_prep[cat_cols])
val_cat   = ohe.transform(val_prep[cat_cols])

encoded_cols = ohe.get_feature_names_out(cat_cols)

train_cat = pd.DataFrame(
    train_cat,
    columns=encoded_cols,
    index=train_prep.index
)

val_cat = pd.DataFrame(
    val_cat,
    columns=encoded_cols,
    index=val_prep.index
)

X_model_train_encoded = pd.concat(
    [train_prep[num_cols], train_cat],
    axis=1
)

X_val_encoded = pd.concat(
    [val_prep[num_cols], val_cat],
    axis=1
)


# 6. Encode target
price_map = {
    "50-100": 0,
    "100-150": 1,
    "150-200": 2,
    "200-250": 3
}

y_model_train_encoded = y_model_train.map(price_map)
y_val_encoded = y_val.map(price_map)


# Validation
print("Model train:", X_model_train_encoded.shape)
print("Validation :", X_val_encoded.shape)

print("Same columns:",
      X_model_train_encoded.columns.equals(X_val_encoded.columns))

print("Train missing:", X_model_train_encoded.isna().sum().sum())
print("Val missing  :", X_val_encoded.isna().sum().sum())

print("\nImputer learned:")
for col, value in zip(impute_cols, imputer.statistics_):
    print(f"{col}: {value}")

Model train: (17973, 27)
Validation : (4494, 27)
Same columns: True
Train missing: 0
Val missing  : 0

Imputer learned:
consume_frequency(weekly): 3-4 times
purchase_channel: Online

In [27]:
# STEP 12: Baseline model comparison

import time
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier


# --------------------------------------------------
# Scale ONLY for Logistic Regression
# --------------------------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_model_train_encoded)
X_val_scaled = scaler.transform(X_val_encoded)


# --------------------------------------------------
# Baseline models
# --------------------------------------------------

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        n_jobs=-1,
        eval_metric="mlogloss"
    ),

    "LightGBM": LGBMClassifier(
        random_state=42,
        n_jobs=-1,
        verbosity=-1
    )
}


results = []

for name, model in models.items():

    start = time.time()

    # Logistic uses scaled data
    if name == "Logistic Regression":
        model.fit(X_train_scaled, y_model_train_encoded)
        preds = model.predict(X_val_scaled)

    # Tree models use original encoded data
    else:
        model.fit(
            X_model_train_encoded,
            y_model_train_encoded
        )
        preds = model.predict(X_val_encoded)

    elapsed = time.time() - start

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_val_encoded, preds),
        "Precision_Macro": precision_score(
            y_val_encoded, preds, average="macro"
        ),
        "Recall_Macro": recall_score(
            y_val_encoded, preds, average="macro"
        ),
        "F1_Macro": f1_score(
            y_val_encoded, preds, average="macro"
        ),
        "F1_Weighted": f1_score(
            y_val_encoded, preds, average="weighted"
        ),
        "Training_Time_sec": elapsed
    })


baseline_results = pd.DataFrame(results)

baseline_results = baseline_results.sort_values(
    "F1_Macro",
    ascending=False
).reset_index(drop=True)

baseline_results.round(4)

,Model,Accuracy,Precision_Macro,Recall_Macro,F1_Macro,F1_Weighted,Training_Time_sec
0,XGBoost,0.9190,0.9191,0.9159,0.9175,0.9190,1.3401
1,LightGBM,0.9179,0.9175,0.9149,0.9162,0.9179,0.8359
2,Random Forest,0.8901,0.8932,0.8861,0.8894,0.8903,3.9987
3,Logistic Regression,0.8498,0.8465,0.8425,0.8445,0.8498,0.3266

In [28]:
# STEP 13: Per-class validation performance

from sklearn.metrics import classification_report

class_names = ["50-100", "100-150", "150-200", "200-250"]

validation_predictions = {}

for name, model in models.items():

    if name == "Logistic Regression":
        preds = model.predict(X_val_scaled)
    else:
        preds = model.predict(X_val_encoded)

    validation_predictions[name] = preds

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    print(
        classification_report(
            y_val_encoded,
            preds,
            target_names=class_names,
            digits=4
        )
    )

============================================================
Logistic Regression
============================================================
              precision    recall  f1-score   support

      50-100     0.8469    0.8175    0.8319       548
     100-150     0.8092    0.8238    0.8164      1169
     150-200     0.8148    0.8098    0.8123      1320
     200-250     0.9152    0.9190    0.9171      1457

    accuracy                         0.8498      4494
   macro avg     0.8465    0.8425    0.8445      4494
weighted avg     0.8498    0.8498    0.8498      4494


============================================================
Random Forest
============================================================
              precision    recall  f1-score   support

      50-100     0.9178    0.8759    0.8964       548
     100-150     0.8762    0.8597    0.8679      1169
     150-200     0.8397    0.8773    0.8581      1320
     200-250     0.9391    0.9314    0.9352      1457

    accuracy                         0.8901      4494
   macro avg     0.8932    0.8861    0.8894      4494
weighted avg     0.8910    0.8901    0.8903      4494


============================================================
XGBoost
============================================================
              precision    recall  f1-score   support

      50-100     0.9290    0.9069    0.9178       548
     100-150     0.9009    0.9025    0.9017      1169
     150-200     0.8926    0.9000    0.8963      1320
     200-250     0.9540    0.9540    0.9540      1457

    accuracy                         0.9190      4494
   macro avg     0.9191    0.9159    0.9175      4494
weighted avg     0.9191    0.9190    0.9190      4494


============================================================
LightGBM
============================================================
              precision    recall  f1-score   support

      50-100     0.9239    0.9088    0.9163       548
     100-150     0.9026    0.8956    0.8991      1169
     150-200     0.8906    0.9000    0.8953      1320
     200-250     0.9528    0.9554    0.9541      1457

    accuracy                         0.9179      4494
   macro avg     0.9175    0.9149    0.9162      4494
weighted avg     0.9179    0.9179    0.9179      4494

In [29]:
from sklearn.metrics import confusion_matrix

for name, preds in validation_predictions.items():

    cm = confusion_matrix(y_val_encoded, preds)

    cm_df = pd.DataFrame(
        cm,
        index=[f"Actual_{c}" for c in class_names],
        columns=[f"Pred_{c}" for c in class_names]
    )

    print(f"\n{name}")
    display(cm_df)

Logistic Regression

                Pred_50-100  Pred_100-150  Pred_150-200  Pred_200-250
Actual_50-100           448           100             0             0
Actual_100-150           81           963           125             0
Actual_150-200            0           127          1069           124
Actual_200-250            0             0           118          1339

Random Forest

                Pred_50-100  Pred_100-150  Pred_150-200  Pred_200-250
Actual_50-100           480            68             0             0
Actual_100-150           43          1005           121             0
Actual_150-200            0            74          1158            88
Actual_200-250            0             0           100          1357

XGBoost

                Pred_50-100  Pred_100-150  Pred_150-200  Pred_200-250
Actual_50-100           497            51             0             0
Actual_100-150           38          1055            76             0
Actual_150-200            0            65          1188            67
Actual_200-250            0             0            67          1390

LightGBM

                Pred_50-100  Pred_100-150  Pred_150-200  Pred_200-250
Actual_50-100           498            50             0             0
Actual_100-150           41          1047            81             0
Actual_150-200            0            63          1188            69
Actual_200-250            0             0            65          1392

In [31]:
import optuna
from xgboost import XGBClassifier
from sklearn.metrics import f1_score

In [32]:
def objective_xgb(trial):

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators", 200, 800
        ),

        "max_depth": trial.suggest_int(
            "max_depth", 3, 8
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate", 0.01, 0.15, log=True
        ),

        "subsample": trial.suggest_float(
            "subsample", 0.7, 1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree", 0.7, 1.0
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight", 1, 8
        ),

        "gamma": trial.suggest_float(
            "gamma", 0.0, 0.5
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha", 1e-4, 1.0, log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda", 0.1, 10.0, log=True
        ),

        "random_state": 42,
        "n_jobs": -1,
        "eval_metric": "mlogloss",
        "verbosity": 0
    }

    model = XGBClassifier(**params)

    model.fit(
        X_model_train_encoded,
        y_model_train_encoded
    )

    preds = model.predict(X_val_encoded)

    return f1_score(
        y_val_encoded,
        preds,
        average="macro"
    )

In [33]:
study_xgb = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42)
)

study_xgb.optimize(
    objective_xgb,
    n_trials=50,
    show_progress_bar=True
)

[I 2026-09-03 14:15:12,763] A new study created in memory with name: no-name-0541cf6e-de9c-41b9-8354-8e0cc35e3d59

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-03 14:15:19,196] Trial 0 finished with value: 0.916001316700431 and parameters: {'n_estimators': 425, 'max_depth': 8, 'learning_rate': 0.07259248719561363, 'subsample': 0.8795975452591109, 'colsample_bytree': 0.7468055921327309, 'min_child_weight': 2, 'gamma': 0.02904180608409973, 'reg_alpha': 0.29154431891537513, 'reg_lambda': 1.5930522616241019}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:15:24,216] Trial 1 finished with value: 0.9145467403062613 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.13826189316223852, 'subsample': 0.9497327922401265, 'colsample_bytree': 0.7637017332034828, 'min_child_weight': 2, 'gamma': 0.09170225492671691, 'reg_alpha': 0.0016480446427978971, 'reg_lambda': 1.1207606211860568}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:15:28,373] Trial 2 finished with value: 0.906960848774214 and parameters: {'n_estimators': 459, 'max_depth': 4, 'learning_rate': 0.05243180891902853, 'subsample': 0.7418481581956126, 'colsample_bytree': 0.7876433945605654, 'min_child_weight': 3, 'gamma': 0.22803499210851796, 'reg_alpha': 0.13826232179369857, 'reg_lambda': 0.2508115686045233}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:15:34,142] Trial 3 finished with value: 0.8750602574910582 and parameters: {'n_estimators': 509, 'max_depth': 6, 'learning_rate': 0.011340440501807348, 'subsample': 0.8822634555704315, 'colsample_bytree': 0.7511572371061874, 'min_child_weight': 1, 'gamma': 0.4744427686266666, 'reg_alpha': 0.7286653737491037, 'reg_lambda': 4.138040112561017}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:15:37,159] Trial 4 finished with value: 0.8864524693524685 and parameters: {'n_estimators': 383, 'max_depth': 3, 'learning_rate': 0.06378528225249058, 'subsample': 0.8320457481218804, 'colsample_bytree': 0.7366114704534336, 'min_child_weight': 4, 'gamma': 0.017194260557609198, 'reg_alpha': 0.43379206974909373, 'reg_lambda': 0.3292759134423616}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:15:42,611] Trial 5 finished with value: 0.9037664533186327 and parameters: {'n_estimators': 598, 'max_depth': 4, 'learning_rate': 0.04089285700048085, 'subsample': 0.8640130838029838, 'colsample_bytree': 0.7554563366576581, 'min_child_weight': 8, 'gamma': 0.3875664116805573, 'reg_alpha': 0.5727904470799616, 'reg_lambda': 6.161049539380966}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:15:50,313] Trial 6 finished with value: 0.901097411013198 and parameters: {'n_estimators': 559, 'max_depth': 8, 'learning_rate': 0.012707942999213693, 'subsample': 0.7587948587257435, 'colsample_bytree': 0.7135681866731614, 'min_child_weight': 3, 'gamma': 0.194338644844741, 'reg_alpha': 0.0012172958098369967, 'reg_lambda': 4.544383960336017}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:15:54,070] Trial 7 finished with value: 0.9002866547647586 and parameters: {'n_estimators': 414, 'max_depth': 4, 'learning_rate': 0.043477055106943, 'subsample': 0.7422772674924287, 'colsample_bytree': 0.9406590942262119, 'min_child_weight': 1, 'gamma': 0.49344346830025865, 'reg_alpha': 0.12273800987852965, 'reg_lambda': 0.24970737145052724}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:15:56,732] Trial 8 finished with value: 0.9121902491791262 and parameters: {'n_estimators': 203, 'max_depth': 7, 'learning_rate': 0.06781546492336318, 'subsample': 0.9187021504122962, 'colsample_bytree': 0.9313811040057838, 'min_child_weight': 1, 'gamma': 0.1792328642721363, 'reg_alpha': 0.00029072088906598463, 'reg_lambda': 5.323617594751501}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:16:01,875] Trial 9 finished with value: 0.8496503452922245 and parameters: {'n_estimators': 574, 'max_depth': 4, 'learning_rate': 0.011878194167382767, 'subsample': 0.7932946965146986, 'colsample_bytree': 0.7975549966080241, 'min_child_weight': 6, 'gamma': 0.31877873567760656, 'reg_alpha': 0.35387588647792356, 'reg_lambda': 0.8798929749689022}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:16:10,960] Trial 10 finished with value: 0.9158544466749108 and parameters: {'n_estimators': 771, 'max_depth': 6, 'learning_rate': 0.02300787305719081, 'subsample': 0.9796871025735361, 'colsample_bytree': 0.8696839272044209, 'min_child_weight': 6, 'gamma': 0.007797399829228058, 'reg_alpha': 0.01163980912248587, 'reg_lambda': 1.3838713864867107}. Best is trial 0 with value: 0.916001316700431.
[I 2026-09-03 14:16:20,421] Trial 11 finished with value: 0.9166022871476596 and parameters: {'n_estimators': 798, 'max_depth': 6, 'learning_rate': 0.024196351546920826, 'subsample': 0.9884016314330396, 'colsample_bytree': 0.8599400537371614, 'min_child_weight': 6, 'gamma': 0.005519126076326512, 'reg_alpha': 0.01721889294312543, 'reg_lambda': 1.525342151796965}. Best is trial 11 with value: 0.9166022871476596.
[I 2026-09-03 14:16:27,029] Trial 12 finished with value: 0.9209564578740723 and parameters: {'n_estimators': 757, 'max_depth': 8, 'learning_rate': 0.13343285407790648, 'subsample': 0.9991551652098886, 'colsample_bytree': 0.8406115656663526, 'min_child_weight': 5, 'gamma': 0.10361528159684316, 'reg_alpha': 0.023089596606847746, 'reg_lambda': 2.052261968843477}. Best is trial 12 with value: 0.9209564578740723.
[I 2026-09-03 14:16:33,714] Trial 13 finished with value: 0.92206920455626 and parameters: {'n_estimators': 798, 'max_depth': 6, 'learning_rate': 0.14193780610446094, 'subsample': 0.9998087315924654, 'colsample_bytree': 0.8489238311686065, 'min_child_weight': 6, 'gamma': 0.12077746649016985, 'reg_alpha': 0.017396296812474163, 'reg_lambda': 2.4693295061233975}. Best is trial 13 with value: 0.92206920455626.
[I 2026-09-03 14:16:39,754] Trial 14 finished with value: 0.9211407963385367 and parameters: {'n_estimators': 695, 'max_depth': 7, 'learning_rate': 0.14793116111105173, 'subsample': 0.998805096808364, 'colsample_bytree': 0.8449878905070604, 'min_child_weight': 5, 'gamma': 0.12533623404482022, 'reg_alpha': 0.02322718353160722, 'reg_lambda': 2.569532796402447}. Best is trial 13 with value: 0.92206920455626.
[I 2026-09-03 14:16:46,969] Trial 15 finished with value: 0.9209163845502325 and parameters: {'n_estimators': 689, 'max_depth': 7, 'learning_rate': 0.10185218157693171, 'subsample': 0.9393059875225248, 'colsample_bytree': 0.8921283575429872, 'min_child_weight': 8, 'gamma': 0.11999044715539643, 'reg_alpha': 0.0035417713163371856, 'reg_lambda': 0.627587133844226}. Best is trial 13 with value: 0.92206920455626.
[I 2026-09-03 14:16:53,080] Trial 16 finished with value: 0.9205365839596945 and parameters: {'n_estimators': 682, 'max_depth': 5, 'learning_rate': 0.09713478796027726, 'subsample': 0.9543720552028452, 'colsample_bytree': 0.81954592982961, 'min_child_weight': 7, 'gamma': 0.26685808387299875, 'reg_alpha': 0.05894682453791556, 'reg_lambda': 0.10625721497327488}. Best is trial 13 with value: 0.92206920455626.
[I 2026-09-03 14:17:00,460] Trial 17 finished with value: 0.9226320533312026 and parameters: {'n_estimators': 709, 'max_depth': 7, 'learning_rate': 0.11161940236925016, 'subsample': 0.9098039681072482, 'colsample_bytree': 0.9069023275635302, 'min_child_weight': 5, 'gamma': 0.14306693354539507, 'reg_alpha': 0.005881585666091681, 'reg_lambda': 9.772041044553248}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:07,242] Trial 18 finished with value: 0.9201455668819513 and parameters: {'n_estimators': 725, 'max_depth': 5, 'learning_rate': 0.09927068134921439, 'subsample': 0.9227727503358069, 'colsample_bytree': 0.9080986200863798, 'min_child_weight': 5, 'gamma': 0.2917166079082988, 'reg_alpha': 0.005593061059202728, 'reg_lambda': 9.294880765417627}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:14,586] Trial 19 finished with value: 0.9197658340922278 and parameters: {'n_estimators': 646, 'max_depth': 7, 'learning_rate': 0.09126830633733067, 'subsample': 0.8295573357999031, 'colsample_bytree': 0.9885618446628731, 'min_child_weight': 7, 'gamma': 0.1580758352180281, 'reg_alpha': 0.00029438796152045154, 'reg_lambda': 9.505356381819388}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:17,307] Trial 20 finished with value: 0.9155137971488378 and parameters: {'n_estimators': 251, 'max_depth': 5, 'learning_rate': 0.10952469564718983, 'subsample': 0.9050696302052489, 'colsample_bytree': 0.9790633353301752, 'min_child_weight': 4, 'gamma': 0.0693849697152994, 'reg_alpha': 0.00011129709953152704, 'reg_lambda': 2.923759727855952}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:23,877] Trial 21 finished with value: 0.9223428360442145 and parameters: {'n_estimators': 722, 'max_depth': 7, 'learning_rate': 0.13177940885632938, 'subsample': 0.9682539844870218, 'colsample_bytree': 0.8410358680553883, 'min_child_weight': 5, 'gamma': 0.13619516878359655, 'reg_alpha': 0.04379082939641084, 'reg_lambda': 2.667591553895528}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:29,794] Trial 22 finished with value: 0.9206798505709242 and parameters: {'n_estimators': 736, 'max_depth': 6, 'learning_rate': 0.14986648737069483, 'subsample': 0.9694521656106433, 'colsample_bytree': 0.8788947421865755, 'min_child_weight': 4, 'gamma': 0.22210185709626518, 'reg_alpha': 0.05750569896770583, 'reg_lambda': 3.2657840012082286}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:40,126] Trial 23 finished with value: 0.9174306044727591 and parameters: {'n_estimators': 795, 'max_depth': 7, 'learning_rate': 0.08019816469128126, 'subsample': 0.7054936594271534, 'colsample_bytree': 0.8212921126226327, 'min_child_weight': 7, 'gamma': 0.0631060567813373, 'reg_alpha': 0.006993700387973725, 'reg_lambda': 6.137971761613895}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:46,324] Trial 24 finished with value: 0.9210342717769864 and parameters: {'n_estimators': 655, 'max_depth': 6, 'learning_rate': 0.12243465566191743, 'subsample': 0.9662947029012023, 'colsample_bytree': 0.9146851909653214, 'min_child_weight': 5, 'gamma': 0.14561251416328616, 'reg_alpha': 0.041719852506640315, 'reg_lambda': 0.617743685202829}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:52,795] Trial 25 finished with value: 0.9221914577409442 and parameters: {'n_estimators': 718, 'max_depth': 7, 'learning_rate': 0.11396334884533868, 'subsample': 0.9385065174479309, 'colsample_bytree': 0.9549077935350732, 'min_child_weight': 6, 'gamma': 0.20744965789503475, 'reg_alpha': 0.0033739183507111086, 'reg_lambda': 2.0880437005514407}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:17:59,829] Trial 26 finished with value: 0.9214299523867663 and parameters: {'n_estimators': 720, 'max_depth': 8, 'learning_rate': 0.08130831385009721, 'subsample': 0.9318889975033695, 'colsample_bytree': 0.9575768334255261, 'min_child_weight': 4, 'gamma': 0.25100558770887016, 'reg_alpha': 0.0020195762689326725, 'reg_lambda': 7.517849982517423}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:18:04,775] Trial 27 finished with value: 0.9189443130459167 and parameters: {'n_estimators': 535, 'max_depth': 7, 'learning_rate': 0.11436385101069269, 'subsample': 0.9071599287186485, 'colsample_bytree': 0.9666419891326025, 'min_child_weight': 5, 'gamma': 0.3316538322481921, 'reg_alpha': 0.004585290095006495, 'reg_lambda': 4.164602397005752}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:18:12,320] Trial 28 finished with value: 0.9193341748998854 and parameters: {'n_estimators': 616, 'max_depth': 8, 'learning_rate': 0.05521736159943586, 'subsample': 0.8931935965293029, 'colsample_bytree': 0.9436613834459942, 'min_child_weight': 6, 'gamma': 0.17743146611941762, 'reg_alpha': 0.0007350404346790485, 'reg_lambda': 1.9230683773291701}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:18:20,964] Trial 29 finished with value: 0.9143158664846391 and parameters: {'n_estimators': 659, 'max_depth': 8, 'learning_rate': 0.08574416905134022, 'subsample': 0.8749251442572392, 'colsample_bytree': 0.9978459820082899, 'min_child_weight': 3, 'gamma': 0.06619914003150534, 'reg_alpha': 0.008236048864684408, 'reg_lambda': 0.8175908773926688}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:18:28,064] Trial 30 finished with value: 0.9212915076898203 and parameters: {'n_estimators': 729, 'max_depth': 7, 'learning_rate': 0.07326444976283247, 'subsample': 0.8389873332670286, 'colsample_bytree': 0.8966587273757525, 'min_child_weight': 7, 'gamma': 0.36438667822292103, 'reg_alpha': 0.003074690268175316, 'reg_lambda': 3.5556166284116615}. Best is trial 17 with value: 0.9226320533312026.
[I 2026-09-03 14:18:35,118] Trial 31 finished with value: 0.9230149165613402 and parameters: {'n_estimators': 764, 'max_depth': 6, 'learning_rate': 0.12440868764193991, 'subsample': 0.9624649557709618, 'colsample_bytree': 0.9267783879010039, 'min_child_weight': 6, 'gamma': 0.14848747900152165, 'reg_alpha': 0.014273453420625977, 'reg_lambda': 2.543923019559772}. Best is trial 31 with value: 0.9230149165613402.
[I 2026-09-03 14:18:41,789] Trial 32 finished with value: 0.9220274615674724 and parameters: {'n_estimators': 759, 'max_depth': 7, 'learning_rate': 0.11611554524523668, 'subsample': 0.9532682116097632, 'colsample_bytree': 0.9218949954903645, 'min_child_weight': 6, 'gamma': 0.20749703721479573, 'reg_alpha': 0.1526831870718741, 'reg_lambda': 1.190104937654223}. Best is trial 31 with value: 0.9230149165613402.
[I 2026-09-03 14:18:48,668] Trial 33 finished with value: 0.9230423603152382 and parameters: {'n_estimators': 700, 'max_depth': 6, 'learning_rate': 0.12034778187740461, 'subsample': 0.9350139863013668, 'colsample_bytree': 0.9552153727216537, 'min_child_weight': 5, 'gamma': 0.13876309692419167, 'reg_alpha': 0.03870751721089646, 'reg_lambda': 1.9028977942385588}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:18:54,965] Trial 34 finished with value: 0.9209052081342233 and parameters: {'n_estimators': 672, 'max_depth': 5, 'learning_rate': 0.1300121227377003, 'subsample': 0.9602281599040396, 'colsample_bytree': 0.8907927835991394, 'min_child_weight': 5, 'gamma': 0.14755045981453468, 'reg_alpha': 0.03558207185498664, 'reg_lambda': 1.6626600075494933}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:02,374] Trial 35 finished with value: 0.9181289928519404 and parameters: {'n_estimators': 625, 'max_depth': 6, 'learning_rate': 0.09360455286934216, 'subsample': 0.9138442587350323, 'colsample_bytree': 0.9757204318702487, 'min_child_weight': 4, 'gamma': 0.06754710006683545, 'reg_alpha': 0.0992970990294591, 'reg_lambda': 0.41991222796495475}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:11,443] Trial 36 finished with value: 0.9186278876939058 and parameters: {'n_estimators': 758, 'max_depth': 6, 'learning_rate': 0.06246571280219745, 'subsample': 0.8909815655904421, 'colsample_bytree': 0.7764544599645736, 'min_child_weight': 5, 'gamma': 0.09818334929675623, 'reg_alpha': 0.22172765384498863, 'reg_lambda': 1.1417309569858687}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:17,713] Trial 37 finished with value: 0.9200471039625082 and parameters: {'n_estimators': 592, 'max_depth': 6, 'learning_rate': 0.12019824049643406, 'subsample': 0.8559601113395702, 'colsample_bytree': 0.9273361259805958, 'min_child_weight': 3, 'gamma': 0.16169044194379567, 'reg_alpha': 0.01083061559073078, 'reg_lambda': 3.115076927744522}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:22,616] Trial 38 finished with value: 0.9166639904618781 and parameters: {'n_estimators': 479, 'max_depth': 5, 'learning_rate': 0.0765572859835032, 'subsample': 0.9740838549752513, 'colsample_bytree': 0.9440697368721042, 'min_child_weight': 4, 'gamma': 0.24833655706828428, 'reg_alpha': 0.032451524368570975, 'reg_lambda': 4.948512156821891}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:31,766] Trial 39 finished with value: 0.9186464679635856 and parameters: {'n_estimators': 710, 'max_depth': 7, 'learning_rate': 0.053904322066769476, 'subsample': 0.9436722367025776, 'colsample_bytree': 0.9046746754426713, 'min_child_weight': 5, 'gamma': 0.04467679389218093, 'reg_alpha': 0.07788994597602539, 'reg_lambda': 6.559819223275037}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:39,467] Trial 40 finished with value: 0.9177174670164864 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.037151426916127335, 'subsample': 0.923519358547346, 'colsample_bytree': 0.7354343801204769, 'min_child_weight': 2, 'gamma': 0.18151127950007848, 'reg_alpha': 0.01385255528660814, 'reg_lambda': 0.8911993029551849}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:46,056] Trial 41 finished with value: 0.9216333082815638 and parameters: {'n_estimators': 709, 'max_depth': 7, 'learning_rate': 0.10694931462161457, 'subsample': 0.9381995115164635, 'colsample_bytree': 0.9574692932980937, 'min_child_weight': 6, 'gamma': 0.19690831139473763, 'reg_alpha': 0.002172685354836226, 'reg_lambda': 1.9686774986163074}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:52,304] Trial 42 finished with value: 0.9211109610351179 and parameters: {'n_estimators': 742, 'max_depth': 7, 'learning_rate': 0.1292960652569857, 'subsample': 0.948450217918285, 'colsample_bytree': 0.9404151835353093, 'min_child_weight': 6, 'gamma': 0.2254938204776329, 'reg_alpha': 0.0008478202994518118, 'reg_lambda': 2.2177387680538}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:19:56,395] Trial 43 finished with value: 0.918040308041569 and parameters: {'n_estimators': 335, 'max_depth': 8, 'learning_rate': 0.10658687240378362, 'subsample': 0.9836685856287922, 'colsample_bytree': 0.956507986853723, 'min_child_weight': 7, 'gamma': 0.13084467891783483, 'reg_alpha': 0.009256350294927254, 'reg_lambda': 3.803683894188184}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:20:03,053] Trial 44 finished with value: 0.9207326637930645 and parameters: {'n_estimators': 779, 'max_depth': 6, 'learning_rate': 0.08682360049650321, 'subsample': 0.8992007827542462, 'colsample_bytree': 0.8802875432946602, 'min_child_weight': 6, 'gamma': 0.4301194397249982, 'reg_alpha': 0.001267427169818754, 'reg_lambda': 1.5041956059924375}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:20:10,271] Trial 45 finished with value: 0.9191956593973806 and parameters: {'n_estimators': 693, 'max_depth': 7, 'learning_rate': 0.13327710677427843, 'subsample': 0.9297492424671742, 'colsample_bytree': 0.9323804982016086, 'min_child_weight': 5, 'gamma': 0.0907185664888339, 'reg_alpha': 0.023851506521122685, 'reg_lambda': 2.6344437573844908}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:20:17,424] Trial 46 finished with value: 0.9201610361870373 and parameters: {'n_estimators': 622, 'max_depth': 6, 'learning_rate': 0.06780226245325059, 'subsample': 0.8739060921034977, 'colsample_bytree': 0.8185240953880084, 'min_child_weight': 4, 'gamma': 0.1723874547264233, 'reg_alpha': 0.003267380276128566, 'reg_lambda': 1.7171606639440042}. Best is trial 33 with value: 0.9230423603152382.
[I 2026-09-03 14:20:28,441] Trial 47 finished with value: 0.9151065033097828 and parameters: {'n_estimators': 771, 'max_depth': 8, 'learning_rate': 0.01568229596416966, 'subsample': 0.9610695590967265, 'colsample_bytree': 0.9722804459055502, 'min_child_weight': 6, 'gamma': 0.030771390370390825, 'reg_alpha': 0.22060337468815328, 'reg_lambda': 4.857874109509123}. Best is trial 33 with value: 0.9230423603152382.

In [34]:
print("Best Macro F1:", study_xgb.best_value)

print("\nBest parameters:")
for k, v in study_xgb.best_params.items():
    print(f"{k}: {v}")

Best Macro F1: 0.9230423603152382

Best parameters:
n_estimators: 700
max_depth: 6
learning_rate: 0.12034778187740461
subsample: 0.9350139863013668
colsample_bytree: 0.9552153727216537
min_child_weight: 5
gamma: 0.13876309692419167
reg_alpha: 0.03870751721089646
reg_lambda: 1.9028977942385588

In [35]:
xgb_trials = study_xgb.trials_dataframe()

xgb_trials[
    [
        "number",
        "value",
        "params_n_estimators",
        "params_max_depth",
        "params_learning_rate",
        "params_subsample",
        "params_colsample_bytree",
        "params_min_child_weight",
        "params_gamma",
        "params_reg_alpha",
        "params_reg_lambda"
    ]
].sort_values(
    "value",
    ascending=False
).head(10)

,number,value,params_n_estimators,params_max_depth,params_learning_rate,params_subsample,params_colsample_bytree,params_min_child_weight,params_gamma,params_reg_alpha,params_reg_lambda
33,33,0.923042,700,6,0.120348,0.935014,0.955215,5,0.138763,0.038708,1.902898
31,31,0.923015,764,6,0.124409,0.962465,0.926778,6,0.148487,0.014273,2.543923
17,17,0.922632,709,7,0.111619,0.909804,0.906902,5,0.143067,0.005882,9.772041
21,21,0.922343,722,7,0.131779,0.968254,0.841036,5,0.136195,0.043791,2.667592
25,25,0.922191,718,7,0.113963,0.938507,0.954908,6,0.207450,0.003374,2.088044
48,48,0.922087,748,7,0.119924,0.979189,0.865049,8,0.206422,0.005647,1.247433
13,13,0.922069,798,6,0.141938,0.999809,0.848924,6,0.120777,0.017396,2.469330
32,32,0.922027,759,7,0.116116,0.953268,0.921895,6,0.207497,0.152683,1.190105
41,41,0.921633,709,7,0.106949,0.938200,0.957469,6,0.196908,0.002173,1.968677
26,26,0.921430,720,8,0.081308,0.931889,0.957577,4,0.251006,0.002020,7.517850

In [36]:
# STEP 15: LightGBM Optuna tuning

import optuna
from lightgbm import LGBMClassifier
from sklearn.metrics import f1_score


def objective_lgbm(trial):

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators", 200, 900
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate", 0.01, 0.15, log=True
        ),

        "num_leaves": trial.suggest_int(
            "num_leaves", 20, 100
        ),

        "max_depth": trial.suggest_int(
            "max_depth", 3, 10
        ),

        "min_child_samples": trial.suggest_int(
            "min_child_samples", 10, 80
        ),

        "subsample": trial.suggest_float(
            "subsample", 0.7, 1.0
        ),

        # Important: otherwise LightGBM may not actually use subsample
        "subsample_freq": 1,

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree", 0.7, 1.0
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha", 1e-4, 1.0, log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda", 0.1, 10.0, log=True
        ),

        "random_state": 42,
        "n_jobs": -1,
        "verbosity": -1
    }

    model = LGBMClassifier(**params)

    model.fit(
        X_model_train_encoded,
        y_model_train_encoded
    )

    preds = model.predict(X_val_encoded)

    return f1_score(
        y_val_encoded,
        preds,
        average="macro"
    )


study_lgbm = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42)
)

study_lgbm.optimize(
    objective_lgbm,
    n_trials=50,
    show_progress_bar=True
)

[I 2026-09-03 14:28:27,235] A new study created in memory with name: no-name-e2de7afc-cf2b-4adc-a6b2-69f58cb6928e

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-03 14:28:32,148] Trial 0 finished with value: 0.9158874372566668 and parameters: {'n_estimators': 462, 'learning_rate': 0.13125830316209655, 'num_leaves': 79, 'max_depth': 7, 'min_child_samples': 21, 'subsample': 0.7467983561008608, 'colsample_bytree': 0.7174250836504598, 'reg_alpha': 0.29154431891537513, 'reg_lambda': 1.5930522616241019}. Best is trial 0 with value: 0.9158874372566668.
[I 2026-09-03 14:28:41,551] Trial 1 finished with value: 0.9109753662771625 and parameters: {'n_estimators': 696, 'learning_rate': 0.010573268083515799, 'num_leaves': 98, 'max_depth': 9, 'min_child_samples': 25, 'subsample': 0.7545474901621302, 'colsample_bytree': 0.7550213529560301, 'reg_alpha': 0.0016480446427978971, 'reg_lambda': 1.1207606211860568}. Best is trial 0 with value: 0.9158874372566668.
[I 2026-09-03 14:28:44,813] Trial 2 finished with value: 0.897942641401612 and parameters: {'n_estimators': 502, 'learning_rate': 0.022004527434741072, 'num_leaves': 69, 'max_depth': 4, 'min_child_samples': 30, 'subsample': 0.8099085529881075, 'colsample_bytree': 0.8368209952651108, 'reg_alpha': 0.13826232179369857, 'reg_lambda': 0.2508115686045233}. Best is trial 0 with value: 0.9158874372566668.
[I 2026-09-03 14:28:49,201] Trial 3 finished with value: 0.9183383024824094 and parameters: {'n_estimators': 560, 'learning_rate': 0.049743185797885274, 'num_leaves': 23, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.7195154778955838, 'colsample_bytree': 0.984665661176, 'reg_alpha': 0.7286653737491037, 'reg_lambda': 4.138040112561017}. Best is trial 3 with value: 0.9183383024824094.
[I 2026-09-03 14:28:52,845] Trial 4 finished with value: 0.8919578574076181 and parameters: {'n_estimators': 413, 'learning_rate': 0.01302780710309028, 'num_leaves': 75, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.848553073033381, 'colsample_bytree': 0.7103165563345655, 'reg_alpha': 0.43379206974909373, 'reg_lambda': 0.3292759134423616}. Best is trial 3 with value: 0.9183383024824094.
[I 2026-09-03 14:28:59,616] Trial 5 finished with value: 0.9136304841130727 and parameters: {'n_estimators': 664, 'learning_rate': 0.02325951592241212, 'num_leaves': 62, 'max_depth': 7, 'min_child_samples': 23, 'subsample': 0.9908753883293675, 'colsample_bytree': 0.9325398470083344, 'reg_alpha': 0.5727904470799616, 'reg_lambda': 6.161049539380966}. Best is trial 3 with value: 0.9183383024824094.
[I 2026-09-03 14:29:03,619] Trial 6 finished with value: 0.9198459190674411 and parameters: {'n_estimators': 619, 'learning_rate': 0.12139707695554378, 'num_leaves': 27, 'max_depth': 4, 'min_child_samples': 13, 'subsample': 0.7975990992289793, 'colsample_bytree': 0.8166031869068446, 'reg_alpha': 0.0012172958098369967, 'reg_lambda': 4.544383960336017}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:06,740] Trial 7 finished with value: 0.8901341058870684 and parameters: {'n_estimators': 450, 'learning_rate': 0.02139954903017622, 'num_leaves': 63, 'max_depth': 4, 'min_child_samples': 66, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9960660809801551, 'reg_alpha': 0.12273800987852965, 'reg_lambda': 0.24970737145052724}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:08,953] Trial 8 finished with value: 0.9164858777616344 and parameters: {'n_estimators': 203, 'learning_rate': 0.09100328259258599, 'num_leaves': 77, 'max_depth': 8, 'min_child_samples': 64, 'subsample': 0.7222133955202271, 'colsample_bytree': 0.8075397185632818, 'reg_alpha': 0.00029072088906598463, 'reg_lambda': 5.323617594751501}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:13,788] Trial 9 finished with value: 0.9126317066892462 and parameters: {'n_estimators': 636, 'learning_rate': 0.02450001073565503, 'num_leaves': 25, 'max_depth': 5, 'min_child_samples': 33, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.8912672414065639, 'reg_alpha': 0.35387588647792356, 'reg_lambda': 0.8798929749689022}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:22,264] Trial 10 finished with value: 0.9151650022134145 and parameters: {'n_estimators': 874, 'learning_rate': 0.06142160992384791, 'num_leaves': 42, 'max_depth': 10, 'min_child_samples': 46, 'subsample': 0.879452623297219, 'colsample_bytree': 0.8268253975058423, 'reg_alpha': 0.009501408054458774, 'reg_lambda': 0.14428528534640284}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:26,406] Trial 11 finished with value: 0.9101542845907397 and parameters: {'n_estimators': 781, 'learning_rate': 0.05705752571961941, 'num_leaves': 20, 'max_depth': 3, 'min_child_samples': 12, 'subsample': 0.802754798121327, 'colsample_bytree': 0.9806685628244274, 'reg_alpha': 0.017344611018880976, 'reg_lambda': 2.841880719237088}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:30,967] Trial 12 finished with value: 0.9158430486893459 and parameters: {'n_estimators': 594, 'learning_rate': 0.044589565017970685, 'num_leaves': 36, 'max_depth': 5, 'min_child_samples': 43, 'subsample': 0.7872409707546499, 'colsample_bytree': 0.8902434624487768, 'reg_alpha': 0.00013625220514033518, 'reg_lambda': 9.611437869807983}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:32,604] Trial 13 finished with value: 0.9081699051952643 and parameters: {'n_estimators': 306, 'learning_rate': 0.14430473604333802, 'num_leaves': 42, 'max_depth': 3, 'min_child_samples': 10, 'subsample': 0.7076648484431629, 'colsample_bytree': 0.9351240089241611, 'reg_alpha': 0.01682687721459112, 'reg_lambda': 2.7503942716171617}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:37,293] Trial 14 finished with value: 0.9175864496256719 and parameters: {'n_estimators': 557, 'learning_rate': 0.0397682841610886, 'num_leaves': 31, 'max_depth': 6, 'min_child_samples': 39, 'subsample': 0.7771714856907851, 'colsample_bytree': 0.7926186735767281, 'reg_alpha': 0.0015030256833470181, 'reg_lambda': 3.036032262967416}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:46,875] Trial 15 finished with value: 0.9166379674276582 and parameters: {'n_estimators': 771, 'learning_rate': 0.09020418967641737, 'num_leaves': 43, 'max_depth': 8, 'min_child_samples': 55, 'subsample': 0.8409402749496258, 'colsample_bytree': 0.8626886507755069, 'reg_alpha': 0.052497082965191164, 'reg_lambda': 4.86407957626018}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:52,519] Trial 16 finished with value: 0.9147049661922048 and parameters: {'n_estimators': 550, 'learning_rate': 0.09409214305768922, 'num_leaves': 49, 'max_depth': 10, 'min_child_samples': 15, 'subsample': 0.9252991708037578, 'colsample_bytree': 0.768088802593119, 'reg_alpha': 0.002323808734427689, 'reg_lambda': 1.7197780422222915}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:29:55,110] Trial 17 finished with value: 0.9033390025573175 and parameters: {'n_estimators': 349, 'learning_rate': 0.03265475256759132, 'num_leaves': 29, 'max_depth': 5, 'min_child_samples': 31, 'subsample': 0.7558549387352061, 'colsample_bytree': 0.9498018762810188, 'reg_alpha': 0.00044658490818635997, 'reg_lambda': 9.86990297509361}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:30:03,058] Trial 18 finished with value: 0.9118742851351789 and parameters: {'n_estimators': 743, 'learning_rate': 0.0688550365709669, 'num_leaves': 52, 'max_depth': 7, 'min_child_samples': 52, 'subsample': 0.8416367725528143, 'colsample_bytree': 0.8958654007917661, 'reg_alpha': 0.005135232608438953, 'reg_lambda': 0.6289111532007959}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:30:08,733] Trial 19 finished with value: 0.919062804977723 and parameters: {'n_estimators': 887, 'learning_rate': 0.113888727265465, 'num_leaves': 21, 'max_depth': 4, 'min_child_samples': 35, 'subsample': 0.7015550393577732, 'colsample_bytree': 0.9576212653850862, 'reg_alpha': 0.9689701697297832, 'reg_lambda': 3.920137383576735}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:30:14,456] Trial 20 finished with value: 0.9196981941586394 and parameters: {'n_estimators': 869, 'learning_rate': 0.10701802652613579, 'num_leaves': 34, 'max_depth': 4, 'min_child_samples': 79, 'subsample': 0.8919527715943093, 'colsample_bytree': 0.8515517058795199, 'reg_alpha': 0.042556535544764344, 'reg_lambda': 2.1243658830458845}. Best is trial 6 with value: 0.9198459190674411.
[I 2026-09-03 14:30:20,198] Trial 21 finished with value: 0.9217171085599549 and parameters: {'n_estimators': 859, 'learning_rate': 0.10895325105561941, 'num_leaves': 33, 'max_depth': 4, 'min_child_samples': 79, 'subsample': 0.9890100579439056, 'colsample_bytree': 0.8551864544771017, 'reg_alpha': 0.047930273427931505, 'reg_lambda': 1.7067169936413789}. Best is trial 21 with value: 0.9217171085599549.
[I 2026-09-03 14:30:24,742] Trial 22 finished with value: 0.9129240566709393 and parameters: {'n_estimators': 816, 'learning_rate': 0.07447222306194007, 'num_leaves': 35, 'max_depth': 3, 'min_child_samples': 79, 'subsample': 0.9968713702888264, 'colsample_bytree': 0.85426894972697, 'reg_alpha': 0.04793455927314174, 'reg_lambda': 1.7995023229700324}. Best is trial 21 with value: 0.9217171085599549.
[I 2026-09-03 14:30:30,337] Trial 23 finished with value: 0.9212000799002078 and parameters: {'n_estimators': 833, 'learning_rate': 0.11272418483582848, 'num_leaves': 35, 'max_depth': 4, 'min_child_samples': 78, 'subsample': 0.9624447019417328, 'colsample_bytree': 0.7961273900472224, 'reg_alpha': 0.03557994113635272, 'reg_lambda': 0.5949346438455735}. Best is trial 21 with value: 0.9217171085599549.
[I 2026-09-03 14:30:36,127] Trial 24 finished with value: 0.9176745764852348 and parameters: {'n_estimators': 714, 'learning_rate': 0.14976194598108114, 'num_leaves': 49, 'max_depth': 5, 'min_child_samples': 72, 'subsample': 0.9627039582952257, 'colsample_bytree': 0.7796412164603375, 'reg_alpha': 0.0006709079081040423, 'reg_lambda': 0.49553053283489756}. Best is trial 21 with value: 0.9217171085599549.
[I 2026-09-03 14:30:41,716] Trial 25 finished with value: 0.9219954059227454 and parameters: {'n_estimators': 823, 'learning_rate': 0.07936035076227366, 'num_leaves': 29, 'max_depth': 4, 'min_child_samples': 71, 'subsample': 0.9622412755183214, 'colsample_bytree': 0.8132549869544614, 'reg_alpha': 0.004766916451540563, 'reg_lambda': 0.9278778864566736}. Best is trial 25 with value: 0.9219954059227454.
[I 2026-09-03 14:30:46,227] Trial 26 finished with value: 0.914619029464278 and parameters: {'n_estimators': 815, 'learning_rate': 0.07604233734677081, 'num_leaves': 38, 'max_depth': 3, 'min_child_samples': 71, 'subsample': 0.9653234843557401, 'colsample_bytree': 0.7379568068113707, 'reg_alpha': 0.0045989985208910785, 'reg_lambda': 0.967396957488874}. Best is trial 25 with value: 0.9219954059227454.
[I 2026-09-03 14:30:54,147] Trial 27 finished with value: 0.9182721105215901 and parameters: {'n_estimators': 820, 'learning_rate': 0.08206623766238681, 'num_leaves': 56, 'max_depth': 6, 'min_child_samples': 73, 'subsample': 0.9540053039354064, 'colsample_bytree': 0.7919789727974879, 'reg_alpha': 0.021942214183039578, 'reg_lambda': 0.5524771306889293}. Best is trial 25 with value: 0.9219954059227454.
[I 2026-09-03 14:31:00,804] Trial 28 finished with value: 0.9208011210468118 and parameters: {'n_estimators': 832, 'learning_rate': 0.10469567591964331, 'num_leaves': 29, 'max_depth': 5, 'min_child_samples': 62, 'subsample': 0.9369077354077915, 'colsample_bytree': 0.8706242459378716, 'reg_alpha': 0.10711882364004098, 'reg_lambda': 1.2497107295382697}. Best is trial 25 with value: 0.9219954059227454.
[I 2026-09-03 14:31:07,006] Trial 29 finished with value: 0.9221964196408547 and parameters: {'n_estimators': 896, 'learning_rate': 0.12638157751864743, 'num_leaves': 44, 'max_depth': 4, 'min_child_samples': 80, 'subsample': 0.9768734381918102, 'colsample_bytree': 0.7539906227680904, 'reg_alpha': 0.007692131246402292, 'reg_lambda': 0.6692146345929244}. Best is trial 29 with value: 0.9221964196408547.
[I 2026-09-03 14:31:11,903] Trial 30 finished with value: 0.9208021842994054 and parameters: {'n_estimators': 886, 'learning_rate': 0.13119784736875964, 'num_leaves': 46, 'max_depth': 3, 'min_child_samples': 59, 'subsample': 0.9840110719924358, 'colsample_bytree': 0.7369328025256202, 'reg_alpha': 0.008737050530270792, 'reg_lambda': 1.3543539960875437}. Best is trial 29 with value: 0.9221964196408547.
[I 2026-09-03 14:31:17,156] Trial 31 finished with value: 0.9218086575641646 and parameters: {'n_estimators': 783, 'learning_rate': 0.11634518699532576, 'num_leaves': 38, 'max_depth': 4, 'min_child_samples': 80, 'subsample': 0.9740304324953224, 'colsample_bytree': 0.8020914927749312, 'reg_alpha': 0.0037525987193640976, 'reg_lambda': 0.68938231202259}. Best is trial 29 with value: 0.9221964196408547.
[I 2026-09-03 14:31:22,256] Trial 32 finished with value: 0.9223663833968606 and parameters: {'n_estimators': 752, 'learning_rate': 0.12741535065931847, 'num_leaves': 95, 'max_depth': 4, 'min_child_samples': 68, 'subsample': 0.9784078582833712, 'colsample_bytree': 0.7510703040726703, 'reg_alpha': 0.0036519195859391557, 'reg_lambda': 0.37782097364722056}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:31:27,915] Trial 33 finished with value: 0.9199642381626414 and parameters: {'n_estimators': 697, 'learning_rate': 0.12777393359918382, 'num_leaves': 94, 'max_depth': 5, 'min_child_samples': 69, 'subsample': 0.9388521494996694, 'colsample_bytree': 0.7517724566107561, 'reg_alpha': 0.0027809679171252647, 'reg_lambda': 0.34991004871187975}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:31:33,045] Trial 34 finished with value: 0.9220139969603905 and parameters: {'n_estimators': 758, 'learning_rate': 0.0943456703149916, 'num_leaves': 57, 'max_depth': 4, 'min_child_samples': 75, 'subsample': 0.9780218994119988, 'colsample_bytree': 0.7351529069935153, 'reg_alpha': 0.005754581080790842, 'reg_lambda': 0.39501783600923446}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:31:37,019] Trial 35 finished with value: 0.910609441342633 and parameters: {'n_estimators': 734, 'learning_rate': 0.06379712496717943, 'num_leaves': 88, 'max_depth': 3, 'min_child_samples': 74, 'subsample': 0.9007064520603401, 'colsample_bytree': 0.7032632742388769, 'reg_alpha': 0.008011498583547837, 'reg_lambda': 0.40911437689873503}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:31:43,765] Trial 36 finished with value: 0.9186330559946683 and parameters: {'n_estimators': 671, 'learning_rate': 0.054168941448516215, 'num_leaves': 84, 'max_depth': 6, 'min_child_samples': 66, 'subsample': 0.9453939493971621, 'colsample_bytree': 0.7342493528416351, 'reg_alpha': 0.001334093742883808, 'reg_lambda': 0.22772139106380665}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:31:50,144] Trial 37 finished with value: 0.9210137426783144 and parameters: {'n_estimators': 763, 'learning_rate': 0.08539018921227842, 'num_leaves': 100, 'max_depth': 5, 'min_child_samples': 59, 'subsample': 0.9758665040887957, 'colsample_bytree': 0.7629897987439687, 'reg_alpha': 0.00744892113844459, 'reg_lambda': 0.1441034895105568}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:31:54,629] Trial 38 finished with value: 0.9204998745961683 and parameters: {'n_estimators': 672, 'learning_rate': 0.09578782801375726, 'num_leaves': 69, 'max_depth': 4, 'min_child_samples': 69, 'subsample': 0.9137865551614939, 'colsample_bytree': 0.7220589908932222, 'reg_alpha': 0.0007987033138391163, 'reg_lambda': 0.8040169692824789}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:31:58,758] Trial 39 finished with value: 0.9193203752825699 and parameters: {'n_estimators': 747, 'learning_rate': 0.1379423482857765, 'num_leaves': 57, 'max_depth': 3, 'min_child_samples': 75, 'subsample': 0.9958581663507221, 'colsample_bytree': 0.7219570148649422, 'reg_alpha': 0.00229247084375242, 'reg_lambda': 0.19227515482291677}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:04,096] Trial 40 finished with value: 0.9211477367370987 and parameters: {'n_estimators': 787, 'learning_rate': 0.07152925024662997, 'num_leaves': 65, 'max_depth': 4, 'min_child_samples': 68, 'subsample': 0.94848128218728, 'colsample_bytree': 0.7744942921636124, 'reg_alpha': 0.010913954612376143, 'reg_lambda': 0.3243345977148091}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:09,448] Trial 41 finished with value: 0.9211754539785868 and parameters: {'n_estimators': 794, 'learning_rate': 0.12477446640317755, 'num_leaves': 93, 'max_depth': 4, 'min_child_samples': 76, 'subsample': 0.9757287486687346, 'colsample_bytree': 0.751457345042938, 'reg_alpha': 0.004626643480811135, 'reg_lambda': 0.7026606999407207}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:14,318] Trial 42 finished with value: 0.9195099352529418 and parameters: {'n_estimators': 716, 'learning_rate': 0.09877867307701316, 'num_leaves': 39, 'max_depth': 4, 'min_child_samples': 80, 'subsample': 0.9726635453213757, 'colsample_bytree': 0.815961841461928, 'reg_alpha': 0.0038345631596887766, 'reg_lambda': 0.9848851326180735}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:20,958] Trial 43 finished with value: 0.9110905963208769 and parameters: {'n_estimators': 840, 'learning_rate': 0.01503168446405911, 'num_leaves': 71, 'max_depth': 5, 'min_child_samples': 62, 'subsample': 0.9299511264396572, 'colsample_bytree': 0.8326139430303381, 'reg_alpha': 0.0027098021621724563, 'reg_lambda': 0.4269031993817795}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:25,264] Trial 44 finished with value: 0.9194979463761425 and parameters: {'n_estimators': 645, 'learning_rate': 0.08267826359997016, 'num_leaves': 60, 'max_depth': 4, 'min_child_samples': 75, 'subsample': 0.999974984371337, 'colsample_bytree': 0.7796359101681326, 'reg_alpha': 0.0009818341878754032, 'reg_lambda': 0.7629301992672474}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:30,189] Trial 45 finished with value: 0.921114240105386 and parameters: {'n_estimators': 900, 'learning_rate': 0.11871845479719005, 'num_leaves': 82, 'max_depth': 3, 'min_child_samples': 72, 'subsample': 0.9554600607085396, 'colsample_bytree': 0.8048022059697821, 'reg_alpha': 0.015010607410055951, 'reg_lambda': 0.2901736643958029}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:35,545] Trial 46 finished with value: 0.9216418906577537 and parameters: {'n_estimators': 792, 'learning_rate': 0.14452045802400287, 'num_leaves': 27, 'max_depth': 4, 'min_child_samples': 66, 'subsample': 0.9788414934487253, 'colsample_bytree': 0.7576212653786109, 'reg_alpha': 0.025934490236753864, 'reg_lambda': 0.10694136210142374}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:43,966] Trial 47 finished with value: 0.9176199321984089 and parameters: {'n_estimators': 857, 'learning_rate': 0.06339082959430918, 'num_leaves': 74, 'max_depth': 6, 'min_child_samples': 77, 'subsample': 0.9108367825127055, 'colsample_bytree': 0.742059856930841, 'reg_alpha': 0.012178246840336991, 'reg_lambda': 0.4989720072514482}. Best is trial 32 with value: 0.9223663833968606.
[I 2026-09-03 14:32:48,770] Trial 48 finished with value: 0.9206901685198792 and parameters: {'n_estimators': 719, 'learning_rate': 0.10209128105662742, 'num_leaves': 24, 'max_depth': 4, 'min_child_samples': 70, 'subsample': 0.9675377591901996, 'colsample_bytree': 0.7119714483276925, 'reg_alpha': 0.005646851702371238, 'reg_lambda': 0.39152258295499426}. Best is trial 32 with value: 0.9223663833968606.

In [37]:
print("Best LightGBM Macro F1:", study_lgbm.best_value)

print("\nBest parameters:")
for k, v in study_lgbm.best_params.items():
    print(f"{k}: {v}")

Best LightGBM Macro F1: 0.9223663833968606

Best parameters:
n_estimators: 752
learning_rate: 0.12741535065931847
num_leaves: 95
max_depth: 4
min_child_samples: 68
subsample: 0.9784078582833712
colsample_bytree: 0.7510703040726703
reg_alpha: 0.0036519195859391557
reg_lambda: 0.37782097364722056

In [38]:
lgbm_trials = study_lgbm.trials_dataframe()

lgbm_trials[
    [
        "number",
        "value",
        "params_n_estimators",
        "params_learning_rate",
        "params_num_leaves",
        "params_max_depth",
        "params_min_child_samples",
        "params_subsample",
        "params_colsample_bytree",
        "params_reg_alpha",
        "params_reg_lambda"
    ]
].sort_values(
    "value",
    ascending=False
).head(10)

,number,value,params_n_estimators,params_learning_rate,params_num_leaves,params_max_depth,params_min_child_samples,params_subsample,params_colsample_bytree,params_reg_alpha,params_reg_lambda
32,32,0.922366,752,0.127415,95,4,68,0.978408,0.751070,0.003652,0.377821
29,29,0.922196,896,0.126382,44,4,80,0.976873,0.753991,0.007692,0.669215
34,34,0.922014,758,0.094346,57,4,75,0.978022,0.735153,0.005755,0.395018
25,25,0.921995,823,0.079360,29,4,71,0.962241,0.813255,0.004767,0.927878
31,31,0.921809,783,0.116345,38,4,80,0.974030,0.802091,0.003753,0.689382
21,21,0.921717,859,0.108953,33,4,79,0.989010,0.855186,0.047930,1.706717
46,46,0.921642,792,0.144520,27,4,66,0.978841,0.757621,0.025934,0.106941
23,23,0.921200,833,0.112724,35,4,78,0.962445,0.796127,0.035580,0.594935
41,41,0.921175,794,0.124774,93,4,76,0.975729,0.751457,0.004627,0.702661
40,40,0.921148,787,0.071529,65,4,68,0.948481,0.774494,0.010914,0.324335

In [39]:
# STEP 16: Random Forest Optuna tuning

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
import optuna


def objective_rf(trial):

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators", 200, 800
        ),

        "max_depth": trial.suggest_categorical(
            "max_depth", [None, 8, 10, 12, 15, 20, 25]
        ),

        "min_samples_split": trial.suggest_int(
            "min_samples_split", 2, 20
        ),

        "min_samples_leaf": trial.suggest_int(
            "min_samples_leaf", 1, 10
        ),

        "max_features": trial.suggest_categorical(
            "max_features",
            ["sqrt", "log2", 0.5, 0.75]
        ),

        "class_weight": trial.suggest_categorical(
            "class_weight",
            [None, "balanced", "balanced_subsample"]
        ),

        "bootstrap": trial.suggest_categorical(
            "bootstrap",
            [True, False]
        ),

        "random_state": 42,
        "n_jobs": -1
    }

    model = RandomForestClassifier(**params)

    model.fit(
        X_model_train_encoded,
        y_model_train_encoded
    )

    preds = model.predict(X_val_encoded)

    return f1_score(
        y_val_encoded,
        preds,
        average="macro"
    )


study_rf = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42)
)

study_rf.optimize(
    objective_rf,
    n_trials=50,
    show_progress_bar=True
)

[I 2026-09-03 14:34:56,182] A new study created in memory with name: no-name-b0e8576f-6430-46df-80b4-4b92d636cfb6

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-03 14:35:01,148] Trial 0 finished with value: 0.8539401091875066 and parameters: {'n_estimators': 425, 'max_depth': None, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'log2', 'class_weight': 'balanced_subsample', 'bootstrap': True}. Best is trial 0 with value: 0.8539401091875066.
[I 2026-09-03 14:35:04,573] Trial 1 finished with value: 0.866099548618144 and parameters: {'n_estimators': 375, 'max_depth': 20, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 'log2', 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 1 with value: 0.866099548618144.
[I 2026-09-03 14:35:14,360] Trial 2 finished with value: 0.8968709185103885 and parameters: {'n_estimators': 611, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 0.5, 'class_weight': None, 'bootstrap': True}. Best is trial 2 with value: 0.8968709185103885.
[I 2026-09-03 14:35:21,444] Trial 3 finished with value: 0.9088097206006163 and parameters: {'n_estimators': 317, 'max_depth': 15, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:35:35,206] Trial 4 finished with value: 0.9010360377330562 and parameters: {'n_estimators': 663, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:35:42,677] Trial 5 finished with value: 0.8857741492008806 and parameters: {'n_estimators': 496, 'max_depth': 20, 'min_samples_split': 11, 'min_samples_leaf': 10, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:35:55,673] Trial 6 finished with value: 0.9084162159558002 and parameters: {'n_estimators': 580, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 0.75, 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:36:04,149] Trial 7 finished with value: 0.9036778118408373 and parameters: {'n_estimators': 402, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 0.75, 'class_weight': None, 'bootstrap': True}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:36:10,183] Trial 8 finished with value: 0.8291620495570147 and parameters: {'n_estimators': 287, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 0.75, 'class_weight': None, 'bootstrap': False}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:36:12,136] Trial 9 finished with value: 0.8742673130751492 and parameters: {'n_estimators': 209, 'max_depth': 25, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2', 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:36:21,190] Trial 10 finished with value: 0.8848021255306755 and parameters: {'n_estimators': 771, 'max_depth': 15, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:36:38,324] Trial 11 finished with value: 0.9048044216639134 and parameters: {'n_estimators': 575, 'max_depth': 25, 'min_samples_split': 16, 'min_samples_leaf': 1, 'max_features': 0.75, 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:36:45,943] Trial 12 finished with value: 0.8542187757344321 and parameters: {'n_estimators': 779, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:37:02,563] Trial 13 finished with value: 0.9084811997141092 and parameters: {'n_estimators': 517, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.75, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 3 with value: 0.9088097206006163.
[I 2026-09-03 14:37:09,694] Trial 14 finished with value: 0.9132078845346865 and parameters: {'n_estimators': 302, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:37:15,867] Trial 15 finished with value: 0.9046237637164474 and parameters: {'n_estimators': 295, 'max_depth': 15, 'min_samples_split': 20, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:37:20,693] Trial 16 finished with value: 0.9039436272542453 and parameters: {'n_estimators': 223, 'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:37:25,706] Trial 17 finished with value: 0.835469864079516 and parameters: {'n_estimators': 321, 'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:37:33,811] Trial 18 finished with value: 0.9108512975630645 and parameters: {'n_estimators': 350, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:37:43,997] Trial 19 finished with value: 0.9078338911682067 and parameters: {'n_estimators': 452, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:37:48,643] Trial 20 finished with value: 0.8912211792307628 and parameters: {'n_estimators': 367, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight': None, 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:37:53,554] Trial 21 finished with value: 0.8704313529320024 and parameters: {'n_estimators': 265, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:00,718] Trial 22 finished with value: 0.9030222755763552 and parameters: {'n_estimators': 331, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:06,298] Trial 23 finished with value: 0.9075589249334258 and parameters: {'n_estimators': 249, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:13,929] Trial 24 finished with value: 0.9107520206308768 and parameters: {'n_estimators': 335, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:22,044] Trial 25 finished with value: 0.909575646849025 and parameters: {'n_estimators': 361, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:32,695] Trial 26 finished with value: 0.9105799260562025 and parameters: {'n_estimators': 449, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:42,528] Trial 27 finished with value: 0.9123906210492353 and parameters: {'n_estimators': 402, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:46,444] Trial 28 finished with value: 0.8100825453772584 and parameters: {'n_estimators': 477, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:51,087] Trial 29 finished with value: 0.8812349210783659 and parameters: {'n_estimators': 431, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'log2', 'class_weight': None, 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:38:54,792] Trial 30 finished with value: 0.8548127235247388 and parameters: {'n_estimators': 386, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 'log2', 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:03,574] Trial 31 finished with value: 0.9074821906625821 and parameters: {'n_estimators': 405, 'max_depth': 15, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:12,098] Trial 32 finished with value: 0.9110070165805304 and parameters: {'n_estimators': 350, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:20,599] Trial 33 finished with value: 0.9108337987314177 and parameters: {'n_estimators': 349, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:26,613] Trial 34 finished with value: 0.9054006565468102 and parameters: {'n_estimators': 281, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': True}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:34,111] Trial 35 finished with value: 0.8705712757545359 and parameters: {'n_estimators': 405, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight': 'balanced_subsample', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:39,739] Trial 36 finished with value: 0.9121122915165261 and parameters: {'n_estimators': 238, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:43,907] Trial 37 finished with value: 0.9083741858105402 and parameters: {'n_estimators': 245, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:46,377] Trial 38 finished with value: 0.8880475905226262 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2', 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:39:51,810] Trial 39 finished with value: 0.908395649281432 and parameters: {'n_estimators': 314, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:40:04,956] Trial 40 finished with value: 0.9067044890456877 and parameters: {'n_estimators': 526, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:40:11,607] Trial 41 finished with value: 0.906821175940679 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:40:17,112] Trial 42 finished with value: 0.9101818607806074 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight': None, 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:40:26,017] Trial 43 finished with value: 0.9116608826603866 and parameters: {'n_estimators': 381, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:40:35,084] Trial 44 finished with value: 0.9121535018035627 and parameters: {'n_estimators': 395, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:40:44,087] Trial 45 finished with value: 0.8977121468763558 and parameters: {'n_estimators': 427, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 0.75, 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:40:50,259] Trial 46 finished with value: 0.8886613676682694 and parameters: {'n_estimators': 479, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:40:59,173] Trial 47 finished with value: 0.9119784036737176 and parameters: {'n_estimators': 387, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:41:07,829] Trial 48 finished with value: 0.8898613325489123 and parameters: {'n_estimators': 691, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'log2', 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.
[I 2026-09-03 14:41:16,351] Trial 49 finished with value: 0.9028997506472098 and parameters: {'n_estimators': 273, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.75, 'class_weight': 'balanced', 'bootstrap': False}. Best is trial 14 with value: 0.9132078845346865.

In [40]:
print("Best RF Macro F1:", study_rf.best_value)

print("\nBest parameters:")
for k, v in study_rf.best_params.items():
    print(f"{k}: {v}")

Best RF Macro F1: 0.9132078845346865

Best parameters:
n_estimators: 302
max_depth: 15
min_samples_split: 2
min_samples_leaf: 3
max_features: 0.5
class_weight: balanced_subsample
bootstrap: False

In [41]:
rf_trials = study_rf.trials_dataframe()

rf_trials[
    [
        "number",
        "value",
        "params_n_estimators",
        "params_max_depth",
        "params_min_samples_split",
        "params_min_samples_leaf",
        "params_max_features",
        "params_class_weight",
        "params_bootstrap"
    ]
].sort_values(
    "value",
    ascending=False
).head(10)

,number,value,params_n_estimators,params_max_depth,params_min_samples_split,params_min_samples_leaf,params_max_features,params_class_weight,params_bootstrap
14,14,0.913208,302,15.0,2,3,0.5,balanced_subsample,False
27,27,0.912391,402,15.0,2,2,0.5,balanced_subsample,False
44,44,0.912154,395,20.0,5,4,0.5,balanced,False
36,36,0.912112,238,15.0,3,3,0.5,balanced,False
47,47,0.911978,387,20.0,8,4,0.5,balanced,False
43,43,0.911661,381,20.0,4,4,0.5,balanced,False
32,32,0.911007,350,15.0,4,1,0.5,balanced_subsample,False
18,18,0.910851,350,NaN,2,4,0.5,balanced_subsample,False
33,33,0.910834,349,15.0,4,1,0.5,balanced_subsample,False
24,24,0.910752,335,15.0,9,2,0.5,balanced_subsample,False

In [42]:
# STEP 17: Logistic Regression Optuna tuning

import optuna
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score


def objective_lr(trial):

    solver = trial.suggest_categorical(
        "solver",
        ["lbfgs", "saga"]
    )

    # Valid penalty choices depend on solver
    if solver == "lbfgs":
        penalty = "l2"
    else:
        penalty = trial.suggest_categorical(
            "penalty",
            ["l1", "l2", "elasticnet"]
        )

    params = {
        "C": trial.suggest_float(
            "C", 1e-3, 100, log=True
        ),

        "solver": solver,

        "penalty": penalty,

        "class_weight": trial.suggest_categorical(
            "class_weight",
            [None, "balanced"]
        ),

        "max_iter": 3000,
        "random_state": 42
    }

    # Only elasticnet requires l1_ratio
    if penalty == "elasticnet":
        params["l1_ratio"] = trial.suggest_float(
            "l1_ratio", 0.0, 1.0
        )

    model = LogisticRegression(**params)

    model.fit(
        X_train_scaled,
        y_model_train_encoded
    )

    preds = model.predict(X_val_scaled)

    return f1_score(
        y_val_encoded,
        preds,
        average="macro"
    )


study_lr = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42)
)

study_lr.optimize(
    objective_lr,
    n_trials=50,
    show_progress_bar=True
)

[I 2026-09-03 14:43:40,348] A new study created in memory with name: no-name-2edb2ea3-3a68-4815-9a87-3ac1a731db74

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-03 14:43:40,748] Trial 0 finished with value: 0.7972449751567905 and parameters: {'solver': 'saga', 'penalty': 'l1', 'C': 0.0060252157362038605, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7972449751567905.
[I 2026-09-03 14:43:41,049] Trial 1 finished with value: 0.8219267910154431 and parameters: {'solver': 'saga', 'penalty': 'l2', 'C': 0.011526449540315618, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8219267910154431.
[I 2026-09-03 14:43:41,432] Trial 2 finished with value: 0.8061408513082259 and parameters: {'solver': 'saga', 'penalty': 'elasticnet', 'C': 0.004982752357076452, 'class_weight': 'balanced', 'l1_ratio': 0.45606998421703593}. Best is trial 1 with value: 0.8219267910154431.
[I 2026-09-03 14:43:41,709] Trial 3 finished with value: 0.8449254955582788 and parameters: {'solver': 'lbfgs', 'C': 0.37253938395788866, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:41,786] Trial 4 finished with value: 0.7888107545309028 and parameters: {'solver': 'lbfgs', 'C': 0.0021147447960615704, 'class_weight': 'balanced'}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:41,883] Trial 5 finished with value: 0.8075821791818117 and parameters: {'solver': 'lbfgs', 'C': 0.0030786517836196197, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:43,017] Trial 6 finished with value: 0.8417670868460329 and parameters: {'solver': 'saga', 'penalty': 'l2', 'C': 2.0540519425388455, 'class_weight': 'balanced'}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:43,353] Trial 7 finished with value: 0.8421651776213358 and parameters: {'solver': 'lbfgs', 'C': 70.45683638454501, 'class_weight': 'balanced'}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:43,711] Trial 8 finished with value: 0.8419731747923612 and parameters: {'solver': 'lbfgs', 'C': 40.679084943595456, 'class_weight': 'balanced'}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:44,176] Trial 9 finished with value: 0.8363169724681212 and parameters: {'solver': 'saga', 'penalty': 'elasticnet', 'C': 0.06078083099681954, 'class_weight': 'balanced', 'l1_ratio': 0.14092422497476265}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:44,418] Trial 10 finished with value: 0.8445464843715887 and parameters: {'solver': 'lbfgs', 'C': 0.3162658715155119, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:44,651] Trial 11 finished with value: 0.8448748993885807 and parameters: {'solver': 'lbfgs', 'C': 0.34606023547409104, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:44,962] Trial 12 finished with value: 0.8438152431700982 and parameters: {'solver': 'lbfgs', 'C': 1.3966515267824844, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:45,180] Trial 13 finished with value: 0.8427197619287923 and parameters: {'solver': 'lbfgs', 'C': 0.15850836771923926, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:45,503] Trial 14 finished with value: 0.8438446588536561 and parameters: {'solver': 'lbfgs', 'C': 3.0232181268505016, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:45,911] Trial 15 finished with value: 0.844594814160114 and parameters: {'solver': 'lbfgs', 'C': 7.344283018381388, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:46,060] Trial 16 finished with value: 0.8352567782126648 and parameters: {'solver': 'lbfgs', 'C': 0.02721341527209063, 'class_weight': None}. Best is trial 3 with value: 0.8449254955582788.
[I 2026-09-03 14:43:46,311] Trial 17 finished with value: 0.8450802428007378 and parameters: {'solver': 'lbfgs', 'C': 0.39761316145415976, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:46,587] Trial 18 finished with value: 0.8448342598552715 and parameters: {'solver': 'lbfgs', 'C': 0.8797221113024646, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:46,939] Trial 19 finished with value: 0.84423387312525 and parameters: {'solver': 'lbfgs', 'C': 7.786621744445404, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:47,098] Trial 20 finished with value: 0.8424922099474088 and parameters: {'solver': 'lbfgs', 'C': 0.07682203836914508, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:47,348] Trial 21 finished with value: 0.8450802428007378 and parameters: {'solver': 'lbfgs', 'C': 0.4044310166189876, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:47,609] Trial 22 finished with value: 0.8442705743478705 and parameters: {'solver': 'lbfgs', 'C': 0.7186318120342958, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:47,813] Trial 23 finished with value: 0.8425683653749694 and parameters: {'solver': 'lbfgs', 'C': 0.18893264360325668, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:47,974] Trial 24 finished with value: 0.8410149412781128 and parameters: {'solver': 'lbfgs', 'C': 0.05645456738151592, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:48,311] Trial 25 finished with value: 0.8444249118436753 and parameters: {'solver': 'lbfgs', 'C': 5.541810059891285, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:49,637] Trial 26 finished with value: 0.8435178600919225 and parameters: {'solver': 'saga', 'penalty': 'l1', 'C': 0.5066540019010376, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:49,859] Trial 27 finished with value: 0.8419847558107896 and parameters: {'solver': 'lbfgs', 'C': 0.13722581290163463, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:50,201] Trial 28 finished with value: 0.8444273549654319 and parameters: {'solver': 'lbfgs', 'C': 17.609231975903903, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:50,749] Trial 29 finished with value: 0.8382405070237691 and parameters: {'solver': 'saga', 'penalty': 'l1', 'C': 0.03535931952287614, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:50,876] Trial 30 finished with value: 0.831487548203097 and parameters: {'solver': 'lbfgs', 'C': 0.014903523918803374, 'class_weight': None}. Best is trial 17 with value: 0.8450802428007378.
[I 2026-09-03 14:43:51,092] Trial 31 finished with value: 0.8454434692331583 and parameters: {'solver': 'lbfgs', 'C': 0.355183391139837, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:51,395] Trial 32 finished with value: 0.8446429608708961 and parameters: {'solver': 'lbfgs', 'C': 1.1105912466039491, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:51,610] Trial 33 finished with value: 0.8436462874610648 and parameters: {'solver': 'lbfgs', 'C': 0.2450116627320404, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:52,983] Trial 34 finished with value: 0.843790037403828 and parameters: {'solver': 'saga', 'penalty': 'elasticnet', 'C': 0.5536624191609608, 'class_weight': None, 'l1_ratio': 0.9789743198977108}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:53,147] Trial 35 finished with value: 0.8423980354928524 and parameters: {'solver': 'lbfgs', 'C': 0.09919122221659402, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:53,459] Trial 36 finished with value: 0.8414564355023667 and parameters: {'solver': 'lbfgs', 'C': 2.326663213154905, 'class_weight': 'balanced'}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:53,745] Trial 37 finished with value: 0.825962866961481 and parameters: {'solver': 'saga', 'penalty': 'l2', 'C': 0.010493368678099831, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:54,019] Trial 38 finished with value: 0.8393337297592974 and parameters: {'solver': 'lbfgs', 'C': 0.4437123916737756, 'class_weight': 'balanced'}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:54,361] Trial 39 finished with value: 0.8447622638347728 and parameters: {'solver': 'lbfgs', 'C': 1.5546100200174333, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:54,702] Trial 40 finished with value: 0.6111631369256896 and parameters: {'solver': 'saga', 'penalty': 'l1', 'C': 0.0011431541785080455, 'class_weight': 'balanced'}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:54,928] Trial 41 finished with value: 0.8438483339314999 and parameters: {'solver': 'lbfgs', 'C': 0.28222948533882863, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:55,147] Trial 42 finished with value: 0.8448864825411044 and parameters: {'solver': 'lbfgs', 'C': 0.36476546393710835, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:55,471] Trial 43 finished with value: 0.8440109126698929 and parameters: {'solver': 'lbfgs', 'C': 3.7617246783062783, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:55,657] Trial 44 finished with value: 0.8418698858303756 and parameters: {'solver': 'lbfgs', 'C': 0.14357738668308845, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:55,952] Trial 45 finished with value: 0.8444730842547129 and parameters: {'solver': 'lbfgs', 'C': 0.9037254388757113, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:56,181] Trial 46 finished with value: 0.838611618977446 and parameters: {'solver': 'lbfgs', 'C': 0.23034693387860675, 'class_weight': 'balanced'}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:56,425] Trial 47 finished with value: 0.8443409000172085 and parameters: {'solver': 'lbfgs', 'C': 0.47640847218836385, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:56,743] Trial 48 finished with value: 0.8440587378659272 and parameters: {'solver': 'lbfgs', 'C': 1.5597279639334025, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.
[I 2026-09-03 14:43:56,897] Trial 49 finished with value: 0.838704091717592 and parameters: {'solver': 'lbfgs', 'C': 0.03312808545229379, 'class_weight': None}. Best is trial 31 with value: 0.8454434692331583.

In [43]:
print("Best Logistic Regression Macro F1:", study_lr.best_value)

print("\nBest parameters:")
for k, v in study_lr.best_params.items():
    print(f"{k}: {v}")

Best Logistic Regression Macro F1: 0.8454434692331583

Best parameters:
solver: lbfgs
C: 0.355183391139837
class_weight: None

In [44]:
lr_trials = study_lr.trials_dataframe()

cols = [
    "number",
    "value",
    "params_C",
    "params_solver",
    "params_penalty",
    "params_class_weight"
]

if "params_l1_ratio" in lr_trials.columns:
    cols.append("params_l1_ratio")

lr_trials[cols].sort_values(
    "value",
    ascending=False
).head(10)

,number,value,params_C,params_solver,params_penalty,params_class_weight,params_l1_ratio
31,31,0.845443,0.355183,lbfgs,NaN,None,NaN
17,17,0.845080,0.397613,lbfgs,NaN,None,NaN
21,21,0.845080,0.404431,lbfgs,NaN,None,NaN
3,3,0.844925,0.372539,lbfgs,NaN,None,NaN
42,42,0.844886,0.364765,lbfgs,NaN,None,NaN
11,11,0.844875,0.346060,lbfgs,NaN,None,NaN
18,18,0.844834,0.879722,lbfgs,NaN,None,NaN
39,39,0.844762,1.554610,lbfgs,NaN,None,NaN
32,32,0.844643,1.110591,lbfgs,NaN,None,NaN
15,15,0.844595,7.344283,lbfgs,NaN,None,NaN

In [45]:
# STEP 18: Final tuned validation comparison

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import pandas as pd


# -----------------------------
# Rebuild tuned models
# -----------------------------

best_xgb = XGBClassifier(
    **study_xgb.best_params,
    random_state=42,
    n_jobs=-1,
    eval_metric="mlogloss",
    verbosity=0
)

best_lgbm = LGBMClassifier(
    **study_lgbm.best_params,
    subsample_freq=1,
    random_state=42,
    n_jobs=-1,
    verbosity=-1
)

best_rf = RandomForestClassifier(
    **study_rf.best_params,
    random_state=42,
    n_jobs=-1
)


# LR needs conditional penalty reconstructed
lr_params = study_lr.best_params.copy()

if lr_params["solver"] == "lbfgs":
    lr_params["penalty"] = "l2"

best_lr = LogisticRegression(
    **lr_params,
    max_iter=3000,
    random_state=42
)


# -----------------------------
# Train + validation prediction
# -----------------------------

best_xgb.fit(
    X_model_train_encoded,
    y_model_train_encoded
)

best_lgbm.fit(
    X_model_train_encoded,
    y_model_train_encoded
)

best_rf.fit(
    X_model_train_encoded,
    y_model_train_encoded
)

best_lr.fit(
    X_train_scaled,
    y_model_train_encoded
)


tuned_predictions = {
    "XGBoost": best_xgb.predict(X_val_encoded),
    "LightGBM": best_lgbm.predict(X_val_encoded),
    "Random Forest": best_rf.predict(X_val_encoded),
    "Logistic Regression": best_lr.predict(X_val_scaled)
}


# -----------------------------
# Final validation metrics
# -----------------------------

results = []

for name, preds in tuned_predictions.items():

    # Since target classes are ordered 0,1,2,3:
    ordinal_mae = abs(
        y_val_encoded.to_numpy() - preds
    ).mean()

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(
            y_val_encoded, preds
        ),
        "Precision_Macro": precision_score(
            y_val_encoded, preds, average="macro"
        ),
        "Recall_Macro": recall_score(
            y_val_encoded, preds, average="macro"
        ),
        "F1_Macro": f1_score(
            y_val_encoded, preds, average="macro"
        ),
        "F1_Weighted": f1_score(
            y_val_encoded, preds, average="weighted"
        ),
        "Ordinal_MAE": ordinal_mae
    })


tuned_leaderboard = pd.DataFrame(results).sort_values(
    ["F1_Macro", "Ordinal_MAE"],
    ascending=[False, True]
).reset_index(drop=True)

tuned_leaderboard.round(4)

,Model,Accuracy,Precision_Macro,Recall_Macro,F1_Macro,F1_Weighted,Ordinal_MAE
0,XGBoost,0.9250,0.9248,0.9215,0.9230,0.9250,0.0750
1,LightGBM,0.9246,0.9235,0.9213,0.9224,0.9246,0.0754
2,Random Forest,0.9126,0.9109,0.9161,0.9132,0.9125,0.0874
3,Logistic Regression,0.8505,0.8475,0.8435,0.8454,0.8505,0.1495

In [46]:
# Copies: final test remains untouched until transformed here
dev_prep = X_dev_raw.copy()
test_prep = X_final_test_raw.copy()

# --------------------------------------------------
# 1. Imputation fitted ONLY on full development set
# --------------------------------------------------

final_imputer = SimpleImputer(strategy="most_frequent")

dev_prep[impute_cols] = final_imputer.fit_transform(
    dev_prep[impute_cols]
)

test_prep[impute_cols] = final_imputer.transform(
    test_prep[impute_cols]
)


# --------------------------------------------------
# 2. cf_ab_score
# --------------------------------------------------

for data in [dev_prep, test_prep]:

    data["cf_num"] = data["consume_frequency(weekly)"].map(cf_map)
    data["ab_num"] = data["awareness_of_other_brands"].map(ab_map)

    data["cf_ab_score"] = (
        data["cf_num"] /
        (data["cf_num"] + data["ab_num"])
    ).round(2)


# --------------------------------------------------
# 3. Drop raw/helper columns
# --------------------------------------------------

drop_cols = [
    "age",
    "cf_num",
    "ab_num",
    "zone_num",
    "income_num"
]

dev_prep = dev_prep.drop(columns=drop_cols)
test_prep = test_prep.drop(columns=drop_cols)


# --------------------------------------------------
# 4. Fixed ordinal mappings
# --------------------------------------------------

for data in [dev_prep, test_prep]:

    data["age_group"] = (
        data["age_group"].astype(str).map(age_group_map)
    )

    data["income_levels"] = (
        data["income_levels"].map(income_map)
    )

    data["health_concerns"] = (
        data["health_concerns"].map(health_map)
    )

    data["consume_frequency(weekly)"] = (
        data["consume_frequency(weekly)"].map(freq_map)
    )

    data["preferable_consumption_size"] = (
        data["preferable_consumption_size"].map(size_map)
    )


# --------------------------------------------------
# 5. OHE fitted ONLY on development set
# --------------------------------------------------

final_cat_cols = dev_prep.select_dtypes(
    include=["object", "category"]
).columns.tolist()

final_num_cols = [
    c for c in dev_prep.columns
    if c not in final_cat_cols
]

final_ohe = OneHotEncoder(
    handle_unknown="ignore",
    drop="first",
    sparse_output=False
)

dev_cat = final_ohe.fit_transform(
    dev_prep[final_cat_cols]
)

test_cat = final_ohe.transform(
    test_prep[final_cat_cols]
)

encoded_cols = final_ohe.get_feature_names_out(
    final_cat_cols
)

dev_cat = pd.DataFrame(
    dev_cat,
    columns=encoded_cols,
    index=dev_prep.index
)

test_cat = pd.DataFrame(
    test_cat,
    columns=encoded_cols,
    index=test_prep.index
)

X_dev_final = pd.concat(
    [dev_prep[final_num_cols], dev_cat],
    axis=1
)

X_test_final = pd.concat(
    [test_prep[final_num_cols], test_cat],
    axis=1
)


# Target
y_dev_final = y_dev.map(price_map)
y_test_final = y_final_test.map(price_map)


print("Development:", X_dev_final.shape)
print("Final test :", X_test_final.shape)

print(
    "Same columns:",
    X_dev_final.columns.equals(X_test_final.columns)
)

print("Dev missing :", X_dev_final.isna().sum().sum())
print("Test missing:", X_test_final.isna().sum().sum())

Development: (22467, 27)
Final test : (7489, 27)
Same columns: True
Dev missing : 0
Test missing: 0

In [47]:
from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

final_xgb = XGBClassifier(
    **study_xgb.best_params,
    random_state=42,
    n_jobs=-1,
    eval_metric="mlogloss",
    verbosity=0
)

# Train on ALL development data
final_xgb.fit(
    X_dev_final,
    y_dev_final
)

# FIRST AND FINAL prediction on holdout test
final_test_pred = final_xgb.predict(
    X_test_final
)


final_metrics = {
    "Accuracy": accuracy_score(
        y_test_final, final_test_pred
    ),
    "Precision_Macro": precision_score(
        y_test_final, final_test_pred, average="macro"
    ),
    "Recall_Macro": recall_score(
        y_test_final, final_test_pred, average="macro"
    ),
    "F1_Macro": f1_score(
        y_test_final, final_test_pred, average="macro"
    ),
    "F1_Weighted": f1_score(
        y_test_final, final_test_pred, average="weighted"
    ),
    "Ordinal_MAE": abs(
        y_test_final.to_numpy() - final_test_pred
    ).mean()
}

pd.Series(final_metrics).round(4)

Accuracy           0.9246
Precision_Macro    0.9237
Recall_Macro       0.9235
F1_Macro           0.9236
F1_Weighted        0.9247
Ordinal_MAE        0.0754
dtype: float64

In [48]:
print(
    classification_report(
        y_test_final,
        final_test_pred,
        target_names=[
            "50-100",
            "100-150",
            "150-200",
            "200-250"
        ],
        digits=4
    )
)

cm = confusion_matrix(
    y_test_final,
    final_test_pred
)

pd.DataFrame(
    cm,
    index=[
        "Actual_50-100",
        "Actual_100-150",
        "Actual_150-200",
        "Actual_200-250"
    ],
    columns=[
        "Pred_50-100",
        "Pred_100-150",
        "Pred_150-200",
        "Pred_200-250"
    ]
)

              precision    recall  f1-score   support

      50-100     0.9265    0.9245    0.9255       914
     100-150     0.9110    0.9091    0.9101      1948
     150-200     0.8958    0.9109    0.9033      2199
     200-250     0.9616    0.9493    0.9554      2428

    accuracy                         0.9246      7489
   macro avg     0.9237    0.9235    0.9236      7489
weighted avg     0.9248    0.9246    0.9247      7489

                Pred_50-100  Pred_100-150  Pred_150-200  Pred_200-250
Actual_50-100           845            69             0             0
Actual_100-150           67          1771           110             0
Actual_150-200            0           104          2003            92
Actual_200-250            0             0           123          2305

In [49]:
# STEP 21: Persist final benchmark artifacts to S3

import boto3
import json
import pandas as pd

s3 = boto3.client("s3")

bucket = "krushang-beverage-ml-2026"


# -----------------------------
# 1. Final evaluation metrics
# -----------------------------

evaluation_summary = {
    "selected_model": "XGBoost",
    "model_selection_metric": "macro_f1",

    "validation_macro_f1": float(study_xgb.best_value),

    "final_test": {
        "accuracy": float(final_metrics["Accuracy"]),
        "precision_macro": float(final_metrics["Precision_Macro"]),
        "recall_macro": float(final_metrics["Recall_Macro"]),
        "f1_macro": float(final_metrics["F1_Macro"]),
        "f1_weighted": float(final_metrics["F1_Weighted"]),
        "ordinal_mae": float(final_metrics["Ordinal_MAE"])
    },

    "data": {
        "development_rows": int(len(X_dev_final)),
        "final_test_rows": int(len(X_test_final)),
        "model_features": int(X_dev_final.shape[1])
    }
}

s3.put_object(
    Bucket=bucket,
    Key="evaluation/xgboost_final_test_metrics.json",
    Body=json.dumps(evaluation_summary, indent=4),
    ContentType="application/json"
)


# -----------------------------
# 2. Confusion matrix
# -----------------------------

cm_df = pd.DataFrame(
    cm,
    index=[
        "Actual_50-100",
        "Actual_100-150",
        "Actual_150-200",
        "Actual_200-250"
    ],
    columns=[
        "Pred_50-100",
        "Pred_100-150",
        "Pred_150-200",
        "Pred_200-250"
    ]
)

s3.put_object(
    Bucket=bucket,
    Key="evaluation/xgboost_final_confusion_matrix.csv",
    Body=cm_df.to_csv(),
    ContentType="text/csv"
)


# -----------------------------
# 3. Best Optuna parameters
# -----------------------------

s3.put_object(
    Bucket=bucket,
    Key="evaluation/xgboost_best_params.json",
    Body=json.dumps(
        study_xgb.best_params,
        indent=4
    ),
    ContentType="application/json"
)


print("Saved:")
print("s3://krushang-beverage-ml-2026/evaluation/xgboost_final_test_metrics.json")
print("s3://krushang-beverage-ml-2026/evaluation/xgboost_final_confusion_matrix.csv")
print("s3://krushang-beverage-ml-2026/evaluation/xgboost_best_params.json")

Saved:
s3://krushang-beverage-ml-2026/evaluation/xgboost_final_test_metrics.json
s3://krushang-beverage-ml-2026/evaluation/xgboost_final_confusion_matrix.csv
s3://krushang-beverage-ml-2026/evaluation/xgboost_best_params.json